import {test,expect} from '@playwright/test';
test.use({timezoneId:'UTC'});
for(const width of [1440,390])test(`typed contract parameters and tenant definition at ${width}px`,async({page,request},info)=>{
 const data=await(await request.get('/api/bootstrap')).json();const c=await(await request.post('/api/contracts',{data:{templateId:data.templates.find(t=>t.currentPublishedVersion).id,customerId:data.customers[0].id,title:'پارامترهای عمومی رابط',owner:'آزمون',amount:100,start:'2026-10-01',end:'2027-10-01',paymentTerms:'آزمون',services:[]}})).json();
 const quote='حداکثر کاربران فعال: ۱۰\nتمدید خودکار: خیر\nامکانات مجاز: read، write';
 let saved=await(await request.post(`/api/contracts/${c.id}/amendments`,{data:{title:'پارامترهای عمومی',body:quote,reason:'آزمون',idempotencyKey:crypto.randomUUID()}})).json(),a=saved.amendments[0];
 for(const action of ['submit','approve']){const r=await request.post(`/api/contracts/${c.id}/amendments/${a.id}/review`,{data:{action,expectedStatus:a.status,expectedRevision:a.workflow.revision,idempotencyKey:crypto.randomUUID(),comment:'بررسی آزمون'}});expect(r.status()).toBe(200);saved=await r.json();a=saved.amendments[0];}
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.setViewportSize({width,height:1000});await page.goto('/#view=contracts');await page.locator(`.contract-link[data-id="${c.id}"]`).click();await page.locator('[data-action="detail-tab"][data-tab="service-limits"]').click();await expect(page.locator('.contract-parameters-workspace')).toBeVisible();
 await page.locator('[data-cp="definition"]').click();const def=page.locator('#contractParameterDefinitionForm');await def.locator('[name="key"]').fill('custom-ui-'+width);await def.locator('[name="label"]').fill('شرط اختصاصی آزمون');await def.locator('[name="unit"]').fill('بله / خیر');await def.locator('[name="type"]').selectOption('boolean');await def.locator('[name="aliases"]').fill('شرط اختصاصی آزمون');await page.locator('[data-cp="save"]').click();await expect(page.locator('.contract-parameters-workspace')).toBeVisible();
 await page.locator('#contractParameterSource').selectOption(a.id);await page.locator('[data-cp="extract"]').click();for(let i=0;i<3;i++)await page.locator(`[data-cp="candidate"][data-index="${i}"]`).click();await expect(page.locator('.parameter-value-row')).toHaveCount(3);await expect(page.locator('.parameter-value-row').filter({has:page.locator('[name="parameterKey"] option:checked[value="auto-renew"]')}).locator('[name="parameterValue"]')).toHaveValue('false');
 await page.locator('[data-cp="save"]').click();await expect(page.locator('.contract-parameter-version')).toHaveCount(1);const state=await(await request.get(`/api/contracts/${c.id}/parameters`)).json();expect(state.outbox).toEqual([]);expect(state.versions[0].values).toHaveLength(3);expect(state.versions[0].validFrom).toBe('2026-09-30T20:30:00.000Z');expect(state.versions[0].validTo).toBe('2027-10-01T20:30:00.000Z');expect(state.versions[0].values.find(v=>v.key==='auto-renew').value).toBe(false);
 expect(await page.locator('.modal').evaluate(e=>e.scrollWidth<=e.clientWidth)).toBeTruthy();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await page.locator('.contract-parameter-version').scrollIntoViewIfNeeded();await page.screenshot({path:info.outputPath(`parameters-${width}.png`)});expect(errors).toEqual([]);
});
