import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
async function fixture(request,title){
 const data=await(await request.get('/api/bootstrap')).json();const c=await(await request.post('/api/contracts',{data:{templateId:data.templates.find(t=>t.currentPublishedVersion).id,customerId:data.customers[0].id,title,owner:'آزمون',amount:1000,start:'2026-10-01',end:'2027-10-01',paymentTerms:'توافقی',services:[]}})).json();
 const p=await(await request.post('/api/pricing-plans',{data:{model:{name:'پیوست نسخه یک',bases:[{id:'base',name:'واحد',unit:'عدد',amount:200,source:'استعلام نمونه'}],items:[{id:'one',title:'خدمت',quantity:10,components:[{baseId:'base',coefficient:1}]}]}}})).json();
 const saved=await(await request.post(`/api/contracts/${c.id}/amendments`,{data:{title:'سند مالی مستقل',reason:'بازبینی',body:'متن محفوظ <script>bad()</script>',pricingPlanId:p.id,pricingPlanRevision:1,expectedPricingBasis:c.amendmentPricingBasis.token}})).json();return {c,a:saved.amendments[0]};
}
async function open(page,c){await page.goto('/#view=contracts');await page.locator('[data-search="contracts"]').fill(c.title);await page.locator('button.contract-link').click();await page.locator('[data-action="detail-tab"][data-tab="document"]').click();await page.locator('[data-amendment-id] > summary').click();}
for(const width of [1440,390])test(`amendment HTML download renders offline and print frame uses the same saved attachment at ${width}px`,async({page,request},testInfo)=>{
 await page.setViewportSize({width,height:width===390?844:1000});await page.addInitScript(()=>{window.print=()=>{window.__printed=true;};});const {c,a}=await fixture(request,'خروجی سند '+width);await open(page,c);
 const [download]=await Promise.all([page.waitForEvent('download'),page.locator('[data-action="download-amendment-document"]').click()]);expect(download.suggestedFilename()).toBe(c.number+'-amendment-1.html');const html=await readFile(await download.path(),'utf8');expect(html).toContain('پیوست مالی ثابت');expect(html).toContain('پیش‌نویس');expect(html).toContain('۲٬۰۰۰ ریال');expect(html).not.toContain('<script>bad()');
 const doc=await page.context().newPage(),network=[];await doc.setViewportSize({width,height:width===390?844:1000});doc.on('request',r=>{if(/^https?:/.test(r.url()))network.push(r.url());});await doc.route('**/*',r=>r.abort());await doc.setContent(html);await doc.evaluate(()=>document.fonts.ready);await expect(doc.locator('[data-export-financial]')).toContainText('۲٬۰۰۰ ریال');await expect(doc.locator('script')).toHaveCount(0);await expect(doc.locator('img[onerror]')).toHaveCount(0);expect(await doc.evaluate(()=>document.fonts.check('14px Vazirmatn','قرارداد'))).toBeTruthy();expect(network).toEqual([]);expect(await doc.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await doc.screenshot({path:testInfo.outputPath('amendment-document-'+width+'.png'),fullPage:true,animations:'disabled'});await doc.close();
 await page.locator('[data-action="print-amendment-document"]').click();await expect(page.locator('iframe.print-frame')).toHaveCount(1);const frame=page.frames().find(f=>f!==page.mainFrame());await frame.waitForFunction(()=>window.__printed===true);expect(await frame.locator('[data-export-financial]').textContent()).toContain('۲٬۰۰۰ ریال');
 const saved=await(await request.get('/api/contracts/'+c.id,{maxRetries:1})).json();expect(saved.amendments[0]).toEqual(a);for(const k of ['snapshot','status','amount'])expect(saved[k]).toEqual(c[k]);
});
test('viewer document actions remain available and late export after leaving detail is discarded',async({page,request})=>{
 const {c,a}=await fixture(request,'دریافت خواندنی');const data=await(await request.get('/api/bootstrap')).json();await page.route('**/api/bootstrap',r=>r.fulfill({json:{...data,access:{mode:'oidc-proxy',identity:{roles:['viewer']}}}}));await open(page,c);await expect(page.locator('[data-action="download-amendment-document"]')).toBeEnabled();await expect(page.locator('[data-action="print-amendment-document"]')).toBeEnabled();await expect(page.locator('[data-action="amendment-decision"]')).toHaveCount(0);
 let release,captured;const gate=new Promise(r=>release=r),capture=new Promise(r=>captured=r);const url=`**/api/contracts/${c.id}/amendments/${a.id}/document`;await page.route(url,async r=>{const response=await r.fetch();captured();await gate;await r.fulfill({response});});let downloads=0;page.on('download',()=>downloads++);await page.locator('[data-action="download-amendment-document"]').click();await capture;await page.locator('[data-action="close-modal"]').first().click();const received=page.waitForResponse(r=>r.url().endsWith('/'+a.id+'/document'));release();await received;await page.waitForTimeout(250);expect(downloads).toBe(0);
});