import{test,expect}from'@playwright/test';import{randomUUID}from'node:crypto';
const unique=t=>t+' '+randomUUID().slice(0,8);
async function templateFixture(request){const response=await request.post('/api/templates',{data:{title:unique('الگوی مسیر سازمانی'),category:'خدمات',description:'آزمون مسیر مستقل',body:'قرارداد {{title}} با {{party}}',stages:[{id:'request',name:'بررسی تدارکات',role:'procurement',slaDays:1,required:true,enabled:true},{id:'budget',name:'تأیید بودجه',role:'finance',slaDays:2,required:true,enabled:true},{id:'signature',name:'تأیید نهایی طرفین',role:'signatory',slaDays:1,required:true,enabled:true}]}});expect(response.status()).toBe(201);const value=await response.json();const published=await request.post('/api/templates/'+value.id+'/publish',{data:{revision:value.revision,templateVersionId:value.templateVersionId}});expect(published.status()).toBe(200);return published.json();}
async function startFromTemplate(page,template){await page.goto('/');await page.locator('#sidebar [data-view=templates]').click();await page.locator('.template-card').filter({hasText:template.title}).locator('[data-action=use-template]').click();await page.locator('[data-action=wizard-next]').click();}
async function enterTerms(page,customer,title){await page.locator('[data-wizard-customer]').selectOption(customer.id);await page.locator('#wizardForm [name=title]').fill(title);await page.locator('#wizardForm [name=amount]').fill('1000');await page.locator('#wizardForm [name=start]').fill('2026-10-01');await page.locator('#wizardForm [name=end]').fill('2027-10-01');await page.locator('[data-action=wizard-next]').click();await page.locator('[data-action=wizard-next]').click();}

test('wizard keeps mandatory template order while allowing an optional stage between approvals',async({page,request})=>{const t=await templateFixture(request),data=await(await request.get('/api/bootstrap')).json();await startFromTemplate(page,t);await enterTerms(page,data.customers[0],unique('ترتیب محفوظ'));const rows=page.locator('[data-stage-row]');await expect(rows).toHaveCount(3);await expect(rows.nth(0).locator('[data-action=stage-down]')).toBeDisabled();await expect(rows.nth(1).locator('[data-action=stage-up]')).toBeDisabled();await expect(rows.nth(2).locator('[data-action=stage-up]')).toBeDisabled();await expect(rows.nth(0).locator('[name=stageRole]')).toBeDisabled();await page.locator('[data-action=stage-add]').click();await rows.last().locator('[name=stageName]').fill('بررسی مدیر حساب');await rows.last().locator('[data-action=stage-up]').click();await expect(rows.nth(2).locator('[name=stageName]')).toHaveValue('بررسی مدیر حساب');await expect(rows.nth(3).locator('[name=stageName]')).toHaveValue('تأیید نهایی طرفین');await expect(rows.nth(1).locator('[data-action=stage-up]')).toBeDisabled();const preview=page.waitForRequest(r=>r.method()==='POST'&&new URL(r.url()).pathname==='/api/contracts/preview');await page.locator('[data-action=wizard-next]').click();const sent=(await preview).postDataJSON();expect(sent.stages.filter(s=>t.stages.some(x=>x.id===s.id)).map(s=>s.id)).toEqual(['request','budget','signature']);await expect(page.locator('.document-paper')).toBeVisible();});

test('a registered contract shows and follows its own template version after another version is published',async({page,request})=>{const t=await templateFixture(request),data=await(await request.get('/api/bootstrap')).json();const response=await request.post('/api/contracts',{data:{templateId:t.id,templateVersionId:t.templateVersionId,customerId:data.customers[0].id,title:unique('گردش مستقل قرارداد'),party:data.customers[0].name,amount:1000,owner:'واحد قراردادها',start:'2026-10-01',end:'2027-10-01',paymentTerms:'پرداخت توافقی',services:[]}});expect(response.status()).toBe(201);let c=await response.json();const original=c.snapshot;const edited=await(await request.put('/api/templates/'+t.id,{data:{...t,title:unique('الگوی نسخه دوم'),stages:[{id:'new-legal',name:'بررسی تازه حقوقی',role:'legal',slaDays:1,required:true,enabled:true}]}})).json();expect((await request.post('/api/templates/'+t.id+'/publish',{data:{revision:edited.revision,templateVersionId:edited.templateVersionId}})).ok()).toBe(true);
await page.goto('/');await page.locator('#sidebar [data-view=contracts]').click();await page.locator('button.contract-link[data-id="'+c.id+'"]').click();const route=page.locator('.workflow-routing');await expect(route).toHaveAttribute('data-workflow-template-version',t.templateVersionId);await expect(route).toContainText(t.title);await expect(route).not.toContainText('بررسی تازه حقوقی');await expect(page.locator('[data-workflow-current]')).toContainText('بررسی تدارکات');await expect(page.locator('[data-workflow-next]')).toContainText('تأیید بودجه');
for(const expected of ['بررسی تدارکات','تأیید بودجه','تأیید نهایی طرفین',null]){await page.locator('[data-action=advance-dialog]').click();await page.locator('#advanceForm [name=comment]').fill('تأیید مرحله در آزمون گردش');const done=page.waitForResponse(r=>r.request().method()==='POST'&&new URL(r.url()).pathname==='/api/contracts/'+c.id+'/advance');await page.locator('[data-action=advance-contract]').click();expect((await done).status()).toBe(200);await expect(page.locator('[data-workflow-current]')).toContainText(expected||'همه مراحل تکمیل شده');c=await(await request.get('/api/contracts/'+c.id)).json();if(expected==='تأیید نهایی طرفین')expect(c.status).toBe('awaiting_signature');expect(c.snapshot).toEqual(original);}
expect(c.status).toBe('active');expect(c.stages.every(s=>s.status==='completed')).toBe(true);await expect(page.locator('[data-action=advance-dialog]')).toHaveCount(0);
});
