import {test,expect} from '@playwright/test';
const tenantId='00000000-0000-0000-0000-000000000001';
for(const width of [1440,390])test(`client content search, status dashboard and pagination at ${width}px`,async({page,request},info)=>{
 const serviceKey='e2e-api-'+width,events=Array.from({length:55},(_,i)=>({eventId:`client-${width}-${i}`,requestId:`req-${width}-${i}`,serviceKey,occurredAt:new Date(Date.now()-7200000+i*1000).toISOString(),method:'POST',path:'/api/orders',statusCode:i===2?503:i===1?429:200,durationMs:10+i,requestBytes:20,responseBytes:30,requestBody:{query:i===2?'needle':'order',password:'never-show-this'},responseBody:{message:'completed'}}));const r=await request.post('/api/telemetry/ingest',{headers:{authorization:'Bearer local-e2e-producer-credential-only-00001','X-Tenant-Id':tenantId},data:{events}});expect(r.status()).toBe(200);
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.setViewportSize({width,height:950});await page.goto('/#view=client');await expect(page.locator('#clientCallRows')).toBeVisible();await page.locator('#clientFilter [name="service"]').fill(serviceKey);await page.locator('#clientFilter button').click();await expect(page.locator('#clientCallRows tbody tr')).toHaveCount(50);await expect(page.locator('#clientResults')).toContainText('P95');await page.locator('[data-client="next"]').click();await expect(page.locator('#clientCallRows tbody tr')).toHaveCount(5);await expect(page.locator('[data-client="next"]')).toBeDisabled();
 await page.locator('#clientFilter [name="q"]').fill('needle');await page.locator('#clientFilter button').click();await expect(page.locator('#clientCallRows tbody tr')).toHaveCount(1);await expect(page.locator('#clientCallRows')).toContainText('503');await page.locator('[data-client="detail"]').click();await expect(page.locator('.client-body').first()).toContainText('[REDACTED]');await expect(page.locator('#modalRoot')).not.toContainText('never-show-this');await page.locator('[data-action="close-modal"]').first().click();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await page.screenshot({path:info.outputPath(`client-panel-${width}.png`)});expect(errors).toEqual([]);
});
for(const width of [1440,390])test(`economic agreement shares and optional customer credit at ${width}px`,async({page,request},info)=>{
 const data=await(await request.get('/api/bootstrap')).json();let c=await(await request.post('/api/contracts',{data:{templateId:data.templates.find(t=>t.currentPublishedVersion).id,customerId:data.customers[0].id,title:'اقتصاد دیجیتال رابط '+width,owner:'آزمون',amount:1000,start:'2026-10-01',end:'2027-10-01',paymentTerms:'آزمون',services:[]}})).json();
 const quote='سهم زیرساخت فن‌آسا ۲۰٪ و توسعه‌دهنده ۸۰٪؛ تسویه روزانه از ۱ اکتبر؛ بدون نگه‌داشت و حداقل انتقال صفر؛ مبنا پس از مالیات و برگشت، نگه‌داشت اختلاف؛ اعتبار بازگشتی اختیاری با سقف ۱۰۰۰ ریال و دوره ۳۰ روز و سند CREDIT-1.';
 let saved=await(await request.post(`/api/contracts/${c.id}/amendments`,{data:{title:'اقتصاد سرویس',body:quote,reason:'آزمون رابط',idempotencyKey:crypto.randomUUID()}})).json(),a=saved.amendments[0];for(const action of ['submit','approve']){saved=await(await request.post(`/api/contracts/${c.id}/amendments/${a.id}/review`,{data:{action,expectedStatus:a.status,expectedRevision:a.workflow.revision,idempotencyKey:crypto.randomUUID(),comment:'بررسی'}})).json();a=saved.amendments[0];}
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.setViewportSize({width,height:1000});await page.goto('/#view=contracts');await page.locator(`.contract-link[data-id="${c.id}"]`).click();await page.locator('[data-action="detail-tab"][data-tab="economics"]').click();await page.locator('#economySource').selectOption(a.id);await page.locator('[data-economy="draft"]').click();const form=page.locator('#economyForm');await expect(form.locator('[name="creditEnabled"]')).not.toBeChecked();await expect(page.locator('#customerCreditFields')).toBeHidden();
 for(const [key,value]of Object.entries({serviceKey:'test-api',validFrom:'2026-10-01T03:30',validTo:'2027-10-01T03:30',effectiveAt:'2026-10-01T03:30',anchor:'2026-10-01T03:30',periodDays:'1',holdDays:'0',minimumPayout:'0',clauseQuote:quote}))await form.locator(`[name="${key}"]`).fill(value);
 const actors=page.locator('.economy-actor');for(const [i,name,key,percent]of [[0,'فن‌آسا','fanasa','20'],[1,'توسعه‌دهنده','provider','79']]){await actors.nth(i).locator('[name="actorKey"]').fill(key);await actors.nth(i).locator('[name="actorName"]').fill(name);await actors.nth(i).locator('[name="actorPercent"]').fill(percent);await actors.nth(i).locator('[name="actorAgreement"]').fill('AGREEMENT-'+i);}await page.locator('[data-economy="save"]').click();await expect(page.locator('#modalRoot')).toContainText('۱۰۰ درصد');await actors.nth(1).locator('[name="actorPercent"]').fill('80');
 if(width===1440){await form.locator('[name="creditEnabled"]').check();await expect(page.locator('#customerCreditFields')).toBeVisible();await form.locator('[name="fundingSource"]').selectOption('rebate');await form.locator('[name="creditCeiling"]').fill('1000');await form.locator('[name="creditPeriodDays"]').fill('30');await form.locator('[name="creditReference"]').fill('CREDIT-1');}
 await page.locator('[data-economy="save"]').click();await expect(page.locator('.economy-version')).toHaveCount(1);const economics=await(await request.get(`/api/contracts/${c.id}/economics`)).json();expect(economics.versions[0].terms.customerCredit.enabled).toBe(width===1440);expect(economics.walletPosted).toBe(false);expect(await page.locator('.modal').evaluate(e=>e.scrollWidth<=e.clientWidth)).toBeTruthy();await page.locator('.economy-version').scrollIntoViewIfNeeded();await page.screenshot({path:info.outputPath(`economy-${width}.png`)});expect(errors).toEqual([]);
 if(width===1440){while(c.status!=='active')c=await(await request.post(`/api/contracts/${c.id}/advance`,{data:{expectedStatus:c.status,expectedStepId:c.stages.find(s=>s.status==='active')?.stepId||null}})).json();expect((await request.post(`/api/contracts/${c.id}/execution/commands`,{data:{action:'start',payload:{reference:'SIGNED-CONTRACT',counterparties:'طرفین',confirmSigned:true,signedDate:'2026-10-01',startDate:c.start,endDate:c.end,amount:1000,advanceLimit:0,direction:'receivable'},expectedRevision:0,idempotencyKey:crypto.randomUUID()}})).status()).toBe(200);await page.locator('[data-economy="sign"]').click();await page.locator('#economyForm [name="reference"]').fill('SIGNED-ECONOMY');await page.locator('#economyForm [name="counterparties"]').fill('طرفین');await page.locator('#economyForm [name="signedDate"]').fill('2026-10-01');await page.locator('#economyForm [name="confirmSigned"]').check();await page.locator('[data-economy="save"]').click();await expect(page.locator('.economy-version')).toContainText('مدرک امضا ثبت شده');await page.locator('[data-economy="settlement"]').first().click();const sf=page.locator('#economyForm');for(const[k,v]of Object.entries({periodStart:'2026-10-01T03:30',periodEnd:'2026-10-02T03:30',collected:'101',refunds:'1',tax:'10',disputed:'10',evidenceReference:'FINANCIAL-REPORT'}))await sf.locator(`[name="${k}"]`).fill(v);await sf.locator('[name="confirmEvidence"]').check();await page.locator('[data-economy="save"]').click();await expect(page.locator('[data-economy="export"]')).toBeVisible();const downloadEvent=page.waitForEvent('download');await page.locator('[data-economy="export"]').click();expect((await downloadEvent).suggestedFilename()).toMatch(/settlement-.*\.json$/);const printed=page.waitForEvent('download');await page.locator('[data-economy="print"]').click();expect((await printed).suggestedFilename()).toMatch(/settlement-.*\.html$/);const current=await(await request.get(`/api/contracts/${c.id}/economics`)).json();const doc=await request.get(`/api/contracts/${c.id}/economics/document?proposalId=${current.settlements[0].id}`);expect(doc.headers()['content-type']).toContain('text/html');expect(await doc.text()).toContain('data:font/woff2;base64');}
});
test('provider onboarding validates required documents and can be submitted',async({page,request})=>{
 const data=await(await request.get('/api/bootstrap')).json();await page.goto('/#view=providers');await expect(page.locator('#providerRows')).not.toContainText('در حال دریافت');await page.locator('[data-provider="create"]').click();const form=page.locator('#providerForm');for(const [key,value]of Object.entries({providerName:'ارائه‌دهنده رابط',actorKey:'e2e-provider',legalReference:'L-DOC',technicalReference:'T-DOC',financialReference:'F-DOC'}))await form.locator(`[name="${key}"]`).fill(value);await form.locator('[name="serviceKey"]').selectOption(data.catalog.services[0].code);await page.locator('[data-provider="save"]').click();await expect(page.locator('.provider-card').filter({hasText:'ارائه‌دهنده رابط'})).toBeVisible();await page.locator('.provider-card').filter({hasText:'ارائه‌دهنده رابط'}).locator('[data-provider="submit"]').click();await expect(page.locator('.provider-card').filter({hasText:'ارائه‌دهنده رابط'})).toContainText('حقوقی');
});
