import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
async function fixture(request,title){
 const data=await(await request.get('/api/bootstrap')).json(),template=data.templates.find(t=>t.currentPublishedVersion);
 let c=await(await request.post('/api/contracts',{data:{templateId:template.id,customerId:data.customers[0].id,title,owner:'آزمون',amount:10000,start:'2026-10-01',end:'2027-10-01',paymentTerms:'شرایط واقعی باید ثبت شوند',services:[]}})).json();
 while(c.status!=='active'){const response=await request.post(`/api/contracts/${c.id}/advance`,{data:{expectedStatus:c.status,expectedStepId:c.stages.find(s=>s.status==='active')?.stepId||null}});expect(response.status()).toBe(200);c=await response.json();}
 return c;
}
async function fill(page,values){for(const [name,value] of Object.entries(values)){const input=page.locator(`#executionForm [name="${name}"]`);if(await input.evaluate(e=>e.tagName==='SELECT'))await input.selectOption(value);else if(await input.getAttribute('type')==='checkbox')await input.check();else await input.fill(String(value));}}
async function save(page){await page.locator('[data-exec="save"]').click();await expect(page.locator('#executionForm')).toHaveCount(0);}
async function section(page,name){await page.locator(`[data-exec="section"][data-section="${name}"]`).click();}
for(const width of [1440,390])test(`signed execution delivery, invoice retry and receipts at ${width}px`,async({page,request},testInfo)=>{
 await page.setViewportSize({width,height:width===390?844:1000});await page.addInitScript(()=>{window.print=()=>{window.__printed=true;};});const errors=[];page.on('pageerror',e=>errors.push(e.message));const c=await fixture(request,`اجرای رابط ${width}`);
 await page.goto('/#view=execution');await page.locator(`[data-action="execution-detail"][data-id="${c.id}"]`).click();await page.locator('[data-exec="start"]').click();
 await fill(page,{reference:'signed-ui-01',counterparties:'نمایندگان دو طرف آزمون',signedDate:'2026-10-01',startDate:'2026-10-01',endDate:'2027-10-01',amount:10000,advanceLimit:0,confirmSigned:true});await save(page);await expect(page.locator('.execution-workspace')).toContainText('در حال اجرا');
 await section(page,'finance');await page.locator('[data-exec="milestone"]').click();await fill(page,{title:'مرحله پذیرش',gross:10000,dueDate:'2026-12-01',condition:'پذیرش کامل'});await save(page);
 await section(page,'items');await page.locator('[data-exec="item"]').click();await fill(page,{title:'تحویل <script>bad()</script>',unit:'بسته',quantity:2,unitPrice:5000,dueDate:'2026-11-01',owner:'واحد استقرار',criteria:'صورتجلسه پذیرش'});await save(page);
 await page.locator('[data-exec="delivery"]').click();await fill(page,{quantity:2,deliveredAt:'2026-10-10',reference:'DEL-UI'});await save(page);
 await page.locator('[data-exec="accept"]').click();await fill(page,{reference:'ACCEPT-UI',comment:'معیارها رعایت شده'});await save(page);await expect(page.locator('.execution-card').first()).toContainText('۲ پذیرفته از ۲');
 await page.screenshot({path:testInfo.outputPath(`execution-delivery-${width}.png`)});
 await section(page,'finance');await page.locator('[data-exec="invoice"]').click();const s=(await(await request.get(`/api/contracts/${c.id}/execution`)).json());await fill(page,{kind:'final',milestoneId:s.milestones[0].id,number:`INV-UI-${width}`,dueDate:'2026-12-01',reference:'INV-UI'});await page.locator('[data-exec-line]').fill('2');await expect(page.locator('#executionInvoicePreview')).toContainText('۱۰٬۰۰۰ ریال');
 const keys=[];let first=true;await page.route(`**/api/contracts/${c.id}/execution/commands`,async route=>{if(route.request().postDataJSON().action!=='invoice'){await route.continue();return;}keys.push(route.request().postDataJSON().idempotencyKey);const response=await route.fetch();expect(response.status()).toBe(200);if(first){first=false;await route.abort('connectionreset');}else await route.fulfill({response});});
 await page.locator('[data-exec="save"]').click();await expect(page.locator('#modalError')).toBeVisible();await expect(page.locator('#executionForm [name="number"]')).toHaveValue(`INV-UI-${width}`);await save(page);expect(keys).toHaveLength(2);expect(keys[0]).toBe(keys[1]);
 await page.locator('[data-exec="invoice-approve"]').click();await fill(page,{reference:'FIN-UI',comment:'تأیید مالی'});await save(page);await page.locator('[data-exec="payment"]').click();await fill(page,{amount:4000,paidAt:'2026-10-10',reference:'PAY-UI-1',method:'حواله'});await save(page);await expect(page.locator('[data-execution-invoice]')).toContainText('۶٬۰۰۰ ریال');
 await page.locator('[data-exec="payment"]').click();await fill(page,{amount:6000,paidAt:'2026-10-11',reference:'PAY-UI-2',method:'حواله'});await save(page);
 const [download]=await Promise.all([page.waitForEvent('download'),page.locator('[data-exec="export"]').click()]);expect(download.suggestedFilename()).toBe(c.number+'-execution.json');
 // CI observed ECONNRESET when reusing the loopback connection after download.
 // Retry only this read on transport reset; business commands keep their guards.
 const saved=await(await request.get(`/api/contracts/${c.id}/execution`,{maxRetries:1})).json();
 const [report]=await Promise.all([page.waitForEvent('download'),page.locator('[data-exec="document"]').click()]);expect(report.suggestedFilename()).toBe(`${c.number}-execution-r${saved.revision}.html`);
 const html=await readFile(await report.path(),'utf8');expect(html).toContain(`INV-UI-${width}`);expect(html).toContain('PAY-UI-1');expect(html).toContain('PAY-UI-2');expect(html).toContain('مرکز رایان');expect(html).not.toContain('<script>bad()');
 const doc=await page.context().newPage(),network=[];await doc.setViewportSize({width,height:width===390?844:1000});doc.on('request',r=>{if(/^https?:/.test(r.url()))network.push(r.url());});await doc.route('**/*',r=>r.abort());await doc.setContent(html);await doc.evaluate(()=>document.fonts.ready);await expect(doc.locator('script')).toHaveCount(0);expect(network).toEqual([]);expect(await doc.evaluate(()=>document.fonts.check('14px Vazirmatn','قرارداد'))).toBeTruthy();expect(await doc.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await doc.screenshot({path:testInfo.outputPath(`execution-report-${width}.png`),fullPage:true});await doc.screenshot({path:testInfo.outputPath(`execution-report-top-${width}.png`)});
 await doc.emulateMedia({media:'print'});expect(await doc.locator('thead').first().evaluate(e=>getComputedStyle(e).display)).toBe('table-header-group');await doc.close();
 await page.locator('[data-exec="print"]').click();await expect.poll(()=>page.frames().some(f=>f.url()==='about:srcdoc')).toBeTruthy();const printFrame=page.frames().find(f=>f.url()==='about:srcdoc');await expect.poll(()=>printFrame.evaluate(()=>window.__printed===true)).toBeTruthy();
 expect(await page.locator('.modal').evaluate(e=>e.scrollWidth<=e.clientWidth)).toBeTruthy();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await page.locator('[data-execution-invoice]').scrollIntoViewIfNeeded();await page.locator('.toast-close').evaluateAll(buttons=>buttons.forEach(b=>b.click()));await page.screenshot({path:testInfo.outputPath(`execution-finance-${width}.png`)});
 await page.locator('[data-exec="close"]').click();await fill(page,{reference:'FINAL-UI',comment:'تسویه و خاتمه پس از پذیرش'});await save(page);await expect(page.locator('.execution-workspace')).toContainText('خاتمه و تسویه‌شده');
 const after=await(await request.get(`/api/contracts/${c.id}`,{maxRetries:1})).json();expect(after.execution.invoices).toHaveLength(1);expect(after.execution.payments).toHaveLength(2);expect(after.execution.history.filter(h=>h.action==='invoice')).toHaveLength(1);expect(after.snapshot).toEqual(c.snapshot);expect(after.amount).toBe(c.amount);expect(errors).toEqual([]);
});
test('viewer can inspect signed execution and export but cannot change it',async({page,request})=>{
 const c=await fixture(request,'اجرای مشاهده‌گر');await request.post(`/api/contracts/${c.id}/execution/commands`,{data:{action:'start',payload:{reference:'signed-viewer',counterparties:'طرفین آزمون',confirmSigned:true,signedDate:'2026-10-01',startDate:'2026-10-01',endDate:'2027-10-01',amount:10000,advanceLimit:0,direction:'payable'},expectedRevision:0,idempotencyKey:crypto.randomUUID()}});
 await page.route('**/api/bootstrap',async r=>{const response=await r.fetch(),data=await response.json();data.access={...data.access,identity:{roles:['viewer'],name:'مشاهده‌گر'}};await r.fulfill({json:data});});
 await page.goto('/#view=execution');await page.locator(`[data-action="execution-detail"][data-id="${c.id}"]`).click();await expect(page.locator('[data-exec="pause"]')).toBeDisabled();await expect(page.locator('[data-exec="close"]')).toBeDisabled();await expect(page.locator('[data-exec="export"]')).toBeEnabled();await section(page,'finance');await expect(page.locator('[data-exec="milestone"]')).toBeDisabled();await expect(page.locator('[data-exec="invoice"]')).toBeDisabled();
 await expect(page.locator('[data-exec="document"]')).toBeEnabled();await expect(page.locator('[data-exec="print"]')).toBeEnabled();
 const [report]=await Promise.all([page.waitForEvent('download'),page.locator('[data-exec="document"]').click()]);expect(await readFile(await report.path(),'utf8')).toContain('signed-viewer');
 let release,captured;const gate=new Promise(r=>release=r),capture=new Promise(r=>captured=r);const url=`**/api/contracts/${c.id}/execution/document?*`;
 await page.route(url,async r=>{const response=await r.fetch();captured();await gate;await r.fulfill({response});});let lateDownloads=0;page.on('download',()=>lateDownloads++);
 await page.locator('[data-exec="document"]').click();await capture;await page.locator('[data-action="close-modal"]').first().click();const received=page.waitForResponse(r=>r.url().includes('/execution/document?'));release();await received;await page.waitForTimeout(250);expect(lateDownloads).toBe(0);await page.unrouteAll({behavior:'wait'});
 await page.locator(`[data-action="execution-detail"][data-id="${c.id}"]`).click();
 await page.route(`**/api/contracts/${c.id}/execution/document?*`,r=>r.fulfill({status:409,json:{error:'اجرای قرارداد تغییر کرده است؛ پرونده را بازخوانی کنید.'}}));await page.locator('[data-exec="document"]').click();await expect(page.locator('#modalError')).toContainText('پرونده را بازخوانی کنید');await expect(page.locator('.execution-workspace')).toBeVisible();
});
