import {test,expect} from '@playwright/test';
const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tehran',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const offset=days=>new Date(+new Date(today+'T12:00:00Z')+days*86400000).toISOString().slice(0,10);
async function fixture(request){
 const data=await(await request.get('/api/bootstrap')).json();let c=await(await request.post('/api/contracts',{data:{templateId:data.templates.find(t=>t.currentPublishedVersion).id,customerId:data.customers[0].id,title:'پیگیری اجرا <script>bad()</script>',owner:'آزمون',amount:10000,start:offset(-60),end:offset(7),paymentTerms:'مدارک واقعی باید ثبت شود',services:[]}})).json();
 while(c.status!=='active'){const r=await request.post(`/api/contracts/${c.id}/advance`,{data:{expectedStatus:c.status,expectedStepId:c.stages.find(s=>s.status==='active')?.stepId||null}});expect(r.status()).toBe(200);c=await r.json();}
 let s;const cmd=async(action,payload)=>{const r=await request.post(`/api/contracts/${c.id}/execution/commands`,{data:{action,payload,expectedRevision:s?.revision||0,idempotencyKey:crypto.randomUUID()}});expect(r.status()).toBe(200);s=await r.json();};
 await cmd('start',{reference:'SIGNED-FOLLOWUP-TEST',counterparties:'طرفین آزمایشی',confirmSigned:true,signedDate:today,startDate:offset(-60),endDate:offset(7),amount:10000,advanceLimit:0,direction:'receivable'});
 await cmd('milestone',{title:'مرحله',gross:10000,dueDate:offset(1),condition:'پذیرش'});await cmd('item',{milestoneId:s.milestones[0].id,title:'تحویل <script>bad()</script>',quantity:2,unit:'بسته',unitPrice:5000,dueDate:offset(-1),owner:'مجری',criteria:'پذیرش'});await cmd('delivery',{itemId:s.items[0].id,quantity:1,deliveredAt:offset(-2),reference:'DEL-1'});await cmd('accept',{id:s.deliveries[0].id,reference:'ACCEPT',comment:'پذیرش'});
 await cmd('invoice',{kind:'progress',number:'INV-FOLLOWUP',milestoneId:s.milestones[0].id,lines:[{itemId:s.items[0].id,quantity:1}],tax:0,retention:500,withholding:100,insurance:100,penalty:0,advanceRecovery:0,dueDate:offset(1),reference:'INV-REF',basis:'مقادیر آزمون'});await cmd('invoice-approve',{id:s.invoices[0].id,reference:'FIN',comment:'تأیید'});await cmd('payment',{invoiceId:s.invoices[0].id,amount:1000,paidAt:today,reference:'PAY-1',method:'آزمون'});
 await cmd('delivery',{itemId:s.items[0].id,quantity:0.5,deliveredAt:today,reference:'DEL-REVIEW'});await cmd('obligation',{title:'تعهد امروز',owner:'مجری',dueDate:today,condition:'صورتجلسه'});await cmd('guarantee',{kind:'performance',amount:1000,reference:'G-14',issuer:'بانک آزمون',beneficiary:'کارفرما',expiryDate:offset(14),condition:'مجوز آزادسازی'});await cmd('issue',{kind:'risk',title:'ریسک عقب‌افتاده',owner:'مدیر حساب',dueDate:offset(-2),impact:'پیگیری با مدرک'});
 return {c,s};
}
for(const [width,role] of [[1440,'contract_admin'],[390,'viewer']])test(`execution follow-up filters, role and paused operations at ${width}px`,async({page,request},testInfo)=>{
 const {c,s}=await fixture(request),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.setViewportSize({width,height:width===390?844:1000});
 if(role==='viewer')await page.route('**/api/bootstrap',async r=>{const response=await r.fetch(),data=await response.json();data.access={...data.access,identity:{roles:['viewer']}};await r.fulfill({json:data});});
 await page.goto('/#view=execution');await page.locator(`[data-action="execution-detail"][data-id="${c.id}"]`).click();await expect(page.locator('.execution-followup-row')).toHaveCount(9);await expect(page.locator('.execution-followup-row').first()).toContainText('ریسک عقب‌افتاده');await expect(page.locator('script:not([src])')).toHaveCount(0);
 await page.locator('[data-exec="followup-filter"][data-filter="overdue"]').click();await expect(page.locator('.execution-followup-row')).toHaveCount(3);await expect(page.locator('.execution-followup-list')).not.toContainText('G-14');
 await page.locator('[data-exec="followup-filter"][data-filter="near"]').click();await expect(page.locator('.execution-followup-row')).toHaveCount(4);await expect(page.locator(`[data-followup-key="guarantee:${s.guarantees[0].id}"]`)).toContainText('G-14');
 await page.locator('[data-exec="followup-filter"][data-filter="review"]').click();await expect(page.locator('.execution-followup-row')).toHaveCount(1);const accept=page.locator('.execution-followup-row [data-exec="accept"]');
 if(role==='viewer')await expect(accept).toBeDisabled();else{
  await accept.click();await expect(page.locator('#executionForm')).toHaveAttribute('data-id',s.deliveries.at(-1).id);await page.locator('[data-exec="back"]').click();
  await page.locator('[data-exec="pause"]').click();await page.locator('#executionForm [name="reference"]').fill('PAUSE-TEST');await page.locator('#executionForm [name="comment"]').fill('توقف توافقی آزمون');await page.locator('[data-exec="save"]').click();await expect(page.locator('#executionForm')).toHaveCount(0);await expect(page.locator('.execution-followup-row')).toContainText('شروع مجدد اجرا');await expect(page.locator('.execution-followup-row button').last()).toBeDisabled();
 }
 await page.locator('[data-exec="followup-filter"][data-filter="finance"]').click();await expect(page.locator('.execution-followup-row')).toHaveCount(3);const payment=page.locator(`[data-followup-key="invoice-payment:${s.invoices[0].id}"]`);await expect(payment).toContainText('۳٬۳۰۰ ریال');
 if(role==='viewer')await expect(payment.locator('[data-exec="payment"]')).toBeDisabled();else{await payment.locator('[data-exec="payment"]').click();await expect(page.locator('#executionForm [name="amount"]')).toHaveValue('3300');await page.locator('[data-exec="back"]').click();}
 expect(await page.locator('.modal').evaluate(e=>e.scrollWidth<=e.clientWidth)).toBeTruthy();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await page.locator('.execution-followup-filters').scrollIntoViewIfNeeded();await page.screenshot({path:testInfo.outputPath(`execution-followups-${width}.png`)});expect(errors).toEqual([]);
 if(role==='contract_admin'){await page.locator('.execution-sections [data-exec="section"][data-section="finance"]').click();await expect(page.locator('[data-exec="invoice"]')).toHaveCount(0);await expect(page.locator('[data-exec="deduction-settle"]')).toBeEnabled();await expect(page.locator('[data-exec="invoice-cancel"]')).toHaveCount(0);}
 const report=await request.get(`/api/contracts/${c.id}/execution/document`,{maxRetries:1});expect(await report.text()).toContain('پیگیری اجرا و اقدام بعدی');const saved=await(await request.get(`/api/contracts/${c.id}`,{maxRetries:1})).json();expect(saved.execution.payments).toHaveLength(1);expect(saved.snapshot).toEqual(c.snapshot);
});
