import {test,expect} from '@playwright/test';
const quote='سقف TPS: ۵؛ burst: ۱۰؛ سهمیه ماهانه: ۱۰۰۰ درخواست';
async function fixture(request){const data=await(await request.get('/api/bootstrap')).json();const c=await(await request.post('/api/contracts',{data:{templateId:data.templates.find(t=>t.currentPublishedVersion).id,customerId:data.customers[0].id,title:'ظرفیت سرویس آزمون',owner:'آزمون',amount:10000,start:'2026-10-01',end:'2027-10-01',paymentTerms:'آزمون',services:[]}})).json();
 // The local signed-terms workflow also accepts reviewed amendments as a source.
 let saved=await(await request.post(`/api/contracts/${c.id}/amendments`,{data:{title:'ظرفیت خریداری‌شده',body:quote,reason:'بند ظرفیت',idempotencyKey:crypto.randomUUID()}})).json();let a=saved.amendments[0];
 for(const action of ['submit','approve']){saved=await(await request.post(`/api/contracts/${c.id}/amendments/${a.id}/review`,{data:{action,expectedStatus:a.status,expectedRevision:a.workflow.revision,idempotencyKey:crypto.randomUUID(),comment:'بررسی آزمون'}})).json();a=saved.amendments[0];}
 return {c,a};}
for(const width of [1440,390])test(`service capacity extraction and unsigned amendment never publishes at ${width}px`,async({page,request},info)=>{
 const {c,a}=await fixture(request),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.setViewportSize({width,height:width===390?844:1000});await page.goto('/#view=contracts');await page.locator(`button.contract-link[data-id="${c.id}"]`).click();await page.locator('[data-action="detail-tab"][data-tab="service-limits"]').click();await expect(page.locator('.service-limits-workspace')).toContainText('اعمال در Gateway تأیید نشده');await page.locator('#serviceLimitSource').selectOption(a.id);await page.locator('[data-sl="extract"]').click();await expect(page.locator('.service-limit-candidate')).toHaveCount(3);
 for(let i=0;i<3;i++)await page.locator(`[data-sl="candidate"][data-index="${i}"]`).click();const form=page.locator('#serviceLimitForm');await expect(form.locator('[name="requestsPerSecond"]')).toHaveValue('5');await expect(form.locator('[name="burstCapacity"]')).toHaveValue('10');await expect(form.locator('[name="monthlyRequests"]')).toHaveValue('1000');await expect(form.locator('[name="clauseQuote"]')).toHaveValue(quote);
 await form.locator('[name="serviceKey"]').fill('organization-api');await form.locator('[name="title"]').fill('سرویس سازمان');await form.locator('[name="productKey"]').fill('organization-fabric');await form.locator('[name="environment"]').fill('development');await form.locator('[name="operationGroup"]').fill('organization');await form.locator('[name="confirmRequestMeter"]').check();await page.locator('[data-sl="save"]').click();await expect(page.locator('.service-limit-version')).toHaveCount(1);await expect(page.locator('.service-limit-version')).toContainText('پیش‌نویس');
 const state=await(await request.get(`/api/contracts/${c.id}/service-limits`)).json();expect(state.outbox).toEqual([]);expect(state.gatewayApplied).toBe(false);expect((await(await request.get(`/api/contracts/${c.id}`)).json()).snapshot).toEqual(c.snapshot);
 expect(await page.locator('.modal').evaluate(e=>e.scrollWidth<=e.clientWidth)).toBeTruthy();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await page.locator('.service-limit-version').scrollIntoViewIfNeeded();await page.screenshot({path:info.outputPath(`service-capacity-${width}.png`)});expect(errors).toEqual([]);
 await page.locator('[data-sl="sign"]').click();await page.locator('#serviceLimitForm [name="reference"]').fill('UNSIGNED-TEST');await page.locator('#serviceLimitForm [name="counterparties"]').fill('طرفین آزمون');await page.locator('#serviceLimitForm [name="confirmSigned"]').check();await page.locator('[data-sl="save"]').click();await expect(page.locator('#modalRoot')).toContainText('ثبت مبنای امضاشده');expect((await(await request.get(`/api/contracts/${c.id}/service-limits`)).json()).outbox).toEqual([]);
 if(width===1440){let active=await(await request.get(`/api/contracts/${c.id}`)).json();while(active.status!=='active'){const r=await request.post(`/api/contracts/${c.id}/advance`,{data:{expectedStatus:active.status,expectedStepId:active.stages.find(s=>s.status==='active')?.stepId||null}});expect(r.status()).toBe(200);active=await r.json();}const start=await request.post(`/api/contracts/${c.id}/execution/commands`,{data:{action:'start',payload:{reference:'SIGNED-UI-FIXTURE',counterparties:'طرفین آزمون',confirmSigned:true,signedDate:'2026-10-01',startDate:c.start,endDate:c.end,amount:10000,advanceLimit:0,direction:'receivable'},expectedRevision:0,idempotencyKey:crypto.randomUUID()}});expect(start.status()).toBe(200);await page.locator('[data-sl="back"]').click();await page.locator('[data-sl="sign"]').click();await page.locator('#serviceLimitForm [name="reference"]').fill('SIGNED-CAPACITY-UI');await page.locator('#serviceLimitForm [name="counterparties"]').fill('طرفین آزمون');await page.locator('#serviceLimitForm [name="confirmSigned"]').check();await page.locator('[data-sl="save"]').click();await expect(page.locator('.service-limit-version')).toContainText('مبنای امضاشده ثبت شد');const signed=await(await request.get(`/api/contracts/${c.id}/service-limits`)).json();expect(signed.outbox).toHaveLength(1);expect(signed.outbox[0].status).toBe('pending');expect(signed.gatewayApplied).toBe(false);}
});
test('viewer can inspect capacity history but cannot extract or sign',async({page,request})=>{const {c}=await fixture(request);await page.route('**/api/bootstrap',async r=>{const response=await r.fetch(),data=await response.json();data.access={...data.access,identity:{roles:['viewer']}};await r.fulfill({json:data});});await page.setViewportSize({width:390,height:844});await page.goto('/#view=contracts');await page.locator(`button.contract-link[data-id="${c.id}"]`).click();await page.locator('[data-action="detail-tab"][data-tab="service-limits"]').click();await expect(page.locator('[data-sl="extract"]')).toBeDisabled();});
