import {test,expect} from '@playwright/test';
const tenant='00000000-0000-0000-0000-000000000002';
for(const width of [1440,390])test(`five Titan pricing links, live clauses and saved proposals at ${width}px`,async({page,request})=>{
  await page.addInitScript(id=>sessionStorage.setItem('neocontract-active-tenant',id),tenant);
  await page.setViewportSize({width,height:width===390?844:1000});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('/#view=titan');await expect(page.locator('[data-p-action="load"]')).toHaveCount(5);
  const data=await(await request.get('/api/pricing-plans',{headers:{'X-Tenant-Id':tenant}})).json();
  const plan=data.find(p=>p.linkedContracts[0]?.intakeId==='titan-01');
  await page.locator(`[data-board-row="titan-01"] [data-p-action="load"]`).click();
  await expect(page.locator('[data-p-field="name"]')).toHaveValue(plan.name);
  const expected=plan.total+plan.model.bases[0].amount;
  await page.locator('[data-p-field="bases.0.amount"]').fill(String(plan.model.bases[0].amount*2));
  await expect(page.locator('[data-p-line="0"]')).toContainText(new Intl.NumberFormat('fa-IR').format(plan.model.items[0].amount*2));
  await expect(page.locator('[data-p-line="1"]')).toContainText(new Intl.NumberFormat('fa-IR').format(plan.model.items[1].amount*2));
  await page.locator('.pricing-proposal-preview summary').click();
  await expect(page.locator('[data-p-proposal]')).toContainText(new Intl.NumberFormat('fa-IR').format(expected)+' ریال');
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
  await page.screenshot({path:`artifacts/titan-pricing-${width}.png`,fullPage:false});
  await page.locator('[data-p-action="save"]').click();await expect(page.locator('[data-p-dirty]')).toHaveText('');
  await page.locator('.pricing-linked [data-action="contract-detail"]').click();
  await expect(page.locator('.pricing-captured')).toContainText(new Intl.NumberFormat('fa-IR').format(expected));
  await page.locator('[data-action="detail-tab"][data-tab="document"]').click();
  await expect(page.locator('.document-paper').first()).toContainText(new Intl.NumberFormat('fa-IR').format(expected)+' ریال');
  await page.locator('[data-action="detail-tab"][data-tab="summary"]').click();
  await page.locator('.modal [data-p-action="load"], [role="dialog"] [data-p-action="load"]').click();
  await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.locator('[data-p-field="name"]')).toHaveValue(plan.name);
  expect(errors).toEqual([]);
});
