import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {createDatabase,DEMO_TENANT_ID,TITAN_TENANT_ID} from '../lib/database.mjs';
import {createStore} from '../lib/store.mjs';
import {createApi} from '../lib/http-api.mjs';
import {redactTelemetry,validateCall,telemetryProducerFromEnv} from '../lib/customer-telemetry.mjs';
import {validateEconomicTerms,economicAllocation,settlementSchedule} from '../lib/digital-economy.mjs';
import {allocateRevenue,percentParts} from '../public/economy-model.js';
import {serviceLimitHash} from '../lib/service-limits.mjs';
import {renderSettlementDocument} from '../lib/settlement-document.mjs';
const actor=(role,tenantId=DEMO_TENANT_ID)=>({tenantId,subject:role,name:role,roles:[role]});
const terms={serviceKey:'test-api',actors:[{key:'fanasa',name:'فن‌آسا',role:'infrastructure',percent:'20',agreementReference:'INFRA-1'},{key:'provider',name:'ارائه‌دهنده',role:'provider',percent:'60',agreementReference:'PROVIDER-1'},{key:'partner',name:'شریک',role:'partner',percent:'20',agreementReference:'PARTNER-1'}],revenueBase:'net_collected',periodDays:1,holdDays:0,anchor:'2026-10-01T00:00:00.000Z',minimumPayout:'0',disputePolicy:'hold-disputed'};
test('exact revenue shares conserve every rial and customer credit is opt-in',()=>{
 assert.equal(percentParts('33.3333'),333333);assert.throws(()=>percentParts(33));assert.throws(()=>percentParts('100.0001'));const t=validateEconomicTerms(terms);assert.deepEqual(t.customerCredit,{enabled:false});
 assert.throws(()=>validateEconomicTerms({...terms,actors:terms.actors.slice(0,2)}),/۱۰۰/);assert.throws(()=>validateEconomicTerms({...terms,customerCredit:{enabled:true}}));
 const credit=validateEconomicTerms({...terms,customerCredit:{enabled:true,fundingSource:'rebate',periodDays:30,ceiling:'1000',reference:'CREDIT-AGREEMENT'}});assert.equal(credit.customerCredit.ceiling,'1000');
 for(const amount of ['0','1','2','101','9007199254740991'])assert.equal(allocateRevenue(amount,terms.actors).reduce((s,a)=>s+BigInt(a.amount),0n),BigInt(amount));
 const a=economicAllocation(t,{collected:'101',refunds:'1',tax:'10',disputed:'10'});assert.equal(a.distributable,'80');assert.equal(a.held,'10');assert.equal(a.balanced,true);assert.deepEqual(a.allocations.map(a=>a.amount),['16','48','16']);
 assert.equal(economicAllocation({...t,disputePolicy:'hold-all'},{collected:'101',refunds:'1',tax:'10',disputed:'10'}).distributable,'0');assert.throws(()=>economicAllocation(t,{collected:'1',refunds:'2',tax:'0',disputed:'0'}));
});
test('operational payload redaction and producer scope never create financial usage',()=>{
 const body=redactTelemetry({password:'secret',nested:{apiKey:'secret',message:'a@b.com Bearer opaque',result:'valid'}});assert.equal(body.password,'[REDACTED]');assert.equal(body.nested.apiKey,'[REDACTED]');assert.equal(body.nested.message,'[REDACTED] Bearer [REDACTED]');assert.equal(body.nested.result,'valid');
 assert.equal(telemetryProducerFromEnv({}),null);const producer=telemetryProducerFromEnv({NEOCONTRACT_TELEMETRY_ENABLED:'true',NEOCONTRACT_TELEMETRY_PRODUCERS:JSON.stringify([{id:'gateway',token:'t'.repeat(32),tenantIds:[DEMO_TENANT_ID]}])});assert.equal(producer.authenticate({authorization:'Bearer '+'t'.repeat(32),'x-tenant-id':DEMO_TENANT_ID}).producerId,'gateway');assert.throws(()=>producer.authenticate({authorization:'Bearer '+'t'.repeat(32),'x-tenant-id':TITAN_TENANT_ID}));assert.throws(()=>validateCall({}));
});
test('due periods exclude proposed periods, stop at amendments and do not auto-fund customer credit',()=>{
 const v={id:'v1',status:'signed',terms:validateEconomicTerms(terms),validFrom:'2026-10-01T00:00:00.000Z',validTo:'2026-11-01T00:00:00.000Z',effectiveAt:'2026-10-01T00:00:00.000Z'};
 const schedule=settlementSchedule([v],[{periodStart:'2026-10-01T00:00:00.000Z',periodEnd:'2026-10-02T00:00:00.000Z'}],{now:Date.parse('2026-10-04T00:00:00Z')});assert.equal(schedule.periods.length,2);assert.equal(schedule.periods[0].customerCreditEnabled,false);assert.equal(schedule.periods[0].status,'awaiting-financial-evidence');assert.equal(settlementSchedule([v],[],{executionStatus:'paused'}).periods.length,0);assert.equal(settlementSchedule([v],[],{now:Date.parse('2026-10-04T00:00:00Z'),limit:1}).truncated,true);
});
test('telemetry search, hourly reports, economic lifecycle and provider reviews are durable and tenant-scoped',{timeout:240000},async()=>{
 const db=await createDatabase({dataDir:'memory://',connectionString:process.env.NEOCONTRACT_CUSTOMER_ECONOMY_ACCEPTANCE_URL}),store=createStore(db,DEMO_TENANT_ID),foreign=createStore(db,TITAN_TENANT_ID);let state;
 try{
  const hour=Math.floor(Date.now()/3600000)*3600000,events=[200,429,503,201].map((statusCode,i)=>({eventId:'test-'+i,requestId:'request-'+i,serviceKey:'test-api',occurredAt:new Date(hour-3600000+i*1000).toISOString(),method:'POST',path:'/service/test',statusCode,durationMs:10+i*100,requestBytes:20,responseBytes:30,requestBody:{query:i===2?'needle':'other',password:'private'},responseBody:{status:'completed'}}));
  const receipts=await store.telemetry.ingest('gateway',events);assert.equal(receipts.receipts.length,4);assert.equal(receipts.financialUsage,false);assert.equal((await store.telemetry.ingest('gateway',events)).receipts.every(r=>r.duplicate),true);await assert.rejects(store.telemetry.ingest('gateway',[{...events[0],statusCode:400}]),/محتوای/);
  const filters={from:new Date(hour-3600000).toISOString(),to:new Date(hour).toISOString()},report=await store.telemetry.report(filters);assert.equal(report.total,4);assert.equal(report.errorRate,.5);assert.equal(report.averageLatencyMs,160);assert.equal(report.p95UpperMs,500);assert.equal(report.timeline[0].limited,1);assert.equal(report.requestBytes,80);
  const boundary=await store.telemetry.report({...filters,from:new Date(hour-3598500).toISOString(),to:new Date(hour-3596500).toISOString()});assert.equal(boundary.total,2);assert.equal(boundary.errorRate,.5);assert.equal(boundary.timeline.reduce((s,p)=>s+p.calls,0),2);
  const page=await store.telemetry.search({...filters,limit:2});assert.equal(page.rows.length,2);const next=await store.telemetry.search({...filters,limit:2,cursor:page.nextCursor});assert.equal(next.rows.length,2);assert.equal(new Set([...page.rows,...next.rows].map(r=>r.event_id)).size,4);await assert.rejects(store.telemetry.search({...filters,status:'200',cursor:page.nextCursor}));assert.equal((await store.telemetry.search({...filters,q:'needle'})).rows.length,1);assert.equal((await store.telemetry.report({...filters,q:'needle'})).total,1);assert.equal((await store.telemetry.detail('test-0')).request_body.password,'[REDACTED]');await assert.rejects(foreign.telemetry.detail('test-0'),/یافت نشد/);assert.equal((await foreign.telemetry.report(filters)).total,0);
  const producer=telemetryProducerFromEnv({NEOCONTRACT_TELEMETRY_ENABLED:'true',NEOCONTRACT_TELEMETRY_PRODUCERS:JSON.stringify([{id:'gateway',token:'t'.repeat(32),tenantIds:[DEMO_TENANT_ID]}])}),api=await createApi({database:db,telemetryProducer:producer,authMode:'local-demo'});
  async function request(headers,payload){let status,value;const req={url:'/api/telemetry/ingest',method:'POST',headers:{host:'localhost',...headers},socket:{remoteAddress:'127.0.0.1'},async*[Symbol.asyncIterator](){yield Buffer.from(JSON.stringify(payload));}};await api.handler(req,{writeHead(s){status=s;},end(b){value=JSON.parse(b);}});return {status,value};}
  assert.equal((await request({}, {events})).status,401);assert.equal((await request({authorization:'Bearer '+'t'.repeat(32),'x-tenant-id':TITAN_TENANT_ID},{events})).status,403);assert.equal((await request({authorization:'Bearer '+'t'.repeat(32),'x-tenant-id':DEMO_TENANT_ID},{events})).status,200);
  await db.query("INSERT INTO contracts.api_calls SELECT tenant_id,'expired-call',producer_id,event_hash,occurred_at-interval '31 days',service_key,request_id,method,path,status_code,duration_ms,request_bytes,response_bytes,request_body,response_body,search_document,received_at FROM contracts.api_calls WHERE tenant_id=$1 AND event_id='test-0'",[DEMO_TENANT_ID]);
  assert.equal((await store.telemetry.prune()).removed,1);assert.equal((await store.telemetry.report(filters)).total,4);
  const data=await store.bootstrap();let c=await store.createContract({templateId:data.templates.find(t=>t.currentPublishedVersion).id,customerId:data.customers[0].id,title:'اقتصاد دیجیتال آزمون',owner:'آزمون',amount:1000,start:'2026-10-01',end:'2027-10-01',paymentTerms:'آزمون',services:[]});
  const quote='سهم زیرساخت ۲۰٪، ارائه‌دهنده ۶۰٪، شریک ۲۰٪؛ تسویه روزانه از ۱ اکتبر؛ اعتبار مشتری غیرفعال.';await db.query("INSERT INTO contracts.contract_documents(tenant_id,contract_id,document_type,file_name,storage_key,mime_type,metadata) VALUES($1,$2,'proposal_revision','economics.md','economics','text/plain',$3)",[DEMO_TENANT_ID,c.id,JSON.stringify({body:quote})]);const source=await store.economics.sourceDocument(c.id);assert.equal(source.source.sha256,serviceLimitHash(quote));
  const draft={action:'draft',payload:{terms,sourceKind:'contract',sourceHash:source.source.sha256,clauseQuote:quote,validFrom:'2026-10-01T00:00:00.000Z',validTo:'2027-10-01T00:00:00.000Z',effectiveAt:'2026-10-01T00:00:00.000Z'},expectedRevision:0,idempotencyKey:randomUUID()};await assert.rejects(store.economics.command(c.id,draft,actor('viewer')));state=await store.economics.command(c.id,draft);assert.deepEqual(await store.economics.command(c.id,draft),state);assert.equal(state.walletPosted,false);assert.deepEqual(state.versions[0].terms.customerCredit,{enabled:false});
  const sign={action:'sign',payload:{versionId:state.versions[0].id,confirmSigned:true,reference:'SIGNED-ECONOMY',counterparties:'طرفین آزمون',signedDate:'2026-10-01'},expectedRevision:state.revision,idempotencyKey:randomUUID()};await assert.rejects(store.economics.command(c.id,sign),/امضاشده/);while(c.status!=='active')c=await store.advance(c.id,{expectedStatus:c.status,expectedStepId:c.stages.find(s=>s.status==='active')?.stepId||null});await store.execution.command(c.id,{action:'start',payload:{reference:'SIGNED-CONTRACT',counterparties:'طرفین',confirmSigned:true,signedDate:'2026-10-01',startDate:c.start,endDate:c.end,amount:1000,advanceLimit:0,direction:'receivable'},expectedRevision:0,idempotencyKey:randomUUID()});
  await assert.rejects(store.economics.command(c.id,sign,actor('finance_reviewer')));state=await store.economics.command(c.id,sign,actor('legal_reviewer'));const v=structuredClone(state.versions[0]);assert.equal((await db.query('SELECT * FROM contracts.economics_outbox WHERE contract_id=$1',[c.id])).rows.length,1);
  const settlement={expectedRevision:state.revision,idempotencyKey:randomUUID(),versionId:v.id,periodStart:'2026-10-01T00:00:00.000Z',periodEnd:'2026-10-02T00:00:00.000Z',collected:'101',refunds:'1',tax:'10',disputed:'10',confirmEvidence:true,evidenceReference:'REVIEWED-FINANCIAL-REPORT'};await assert.rejects(store.economics.proposeSettlement(c.id,settlement,actor('account_manager')));state=await store.economics.proposeSettlement(c.id,settlement,actor('finance_reviewer'));assert.equal(state.settlements.length,1);assert.equal(state.settlements[0].proposal.allocation.balanced,true);assert.equal(state.settlements[0].proposal.customerCreditInstruction,null);assert.equal(state.settlements[0].proposal.walletPosted,false);assert.deepEqual(await store.economics.proposeSettlement(c.id,settlement,actor('finance_reviewer')),state);await assert.rejects(store.economics.proposeSettlement(c.id,{...settlement,collected:'102'},actor('finance_reviewer')),/کلید/);await assert.rejects(foreign.economics.read(c.id),/یافت نشد/);
  await assert.rejects(db.query("UPDATE contracts.contract_economics SET revision=revision+1,state=jsonb_set(state,'{versions,0,terms,actors,0,percent}','\"99\"') WHERE contract_id=$1",[c.id]),/immutable/i);await assert.rejects(db.query('DELETE FROM contracts.settlement_proposals WHERE contract_id=$1',[c.id]),/immutable/i);
  const document=renderSettlementDocument(c,state.settlements[0].proposal);assert.match(document,/data:font\/woff2;base64/);assert.match(document,/<svg/);assert.match(document,/در انتظار حسابداری مرکزی/);assert.match(document,/غیرفعال/);
  const svc=data.catalog.services[0].code;const create={action:'create',expectedRevision:0,idempotencyKey:randomUUID(),payload:{providerName:'ارائه‌دهنده آزمون',actorKey:'provider',serviceKey:svc,legalReference:'LEGAL-DOC',financialReference:'FIN-DOC',technicalReference:'TECH-DOC'}};let providers=await store.providers.command(create,actor('account_manager')),application=providers[0];assert.deepEqual(await store.providers.command(create,actor('account_manager')),providers);assert.equal((await foreign.providers.list()).length,0);
  async function command(action,payload={},role='contract_admin'){providers=await store.providers.command({action,applicationId:application.id,expectedRevision:application.revision,idempotencyKey:randomUUID(),payload},actor(role));application=providers.find(a=>a.id===application.id);}
  await command('submit',{},'account_manager');await assert.rejects(command('review',{comment:'تأیید',reference:'R'},'finance_reviewer'));await command('review',{comment:'حقوقی تأیید',reference:'L'},'legal_reviewer');await command('review',{comment:'مالی تأیید',reference:'F'},'finance_reviewer');await assert.rejects(command('review',{comment:'تأیید',reference:'T'},'legal_reviewer'));await command('review',{comment:'فنی تأیید',reference:'T'});assert.equal(application.status,'approved');assert.equal(application.provisioned,false);await assert.rejects(command('prepare',{contractId:c.id,versionId:v.id,reference:'P'}),/همین سرویس/);
  const amendmentQuote='اصلاح سهم‌ها برای سرویس '+svc+'؛ زیرساخت ۲۵٪، ارائه‌دهنده ۵۵٪، شریک ۲۰٪؛ شارژ مشتری غیرفعال.';
  let changed=await store.amend(c.id,{title:'اصلاح سهم سرویس',body:amendmentQuote,reason:'توافق جدید',idempotencyKey:randomUUID()}),amendment=changed.amendments[0];const amendDraft={action:'draft',expectedRevision:state.revision,idempotencyKey:randomUUID(),payload:{...draft.payload,sourceKind:'amendment',amendmentId:amendment.id,sourceHash:serviceLimitHash(amendmentQuote),clauseQuote:amendmentQuote,effectiveAt:'2026-10-15T00:00:00.000Z',terms:{...terms,serviceKey:svc,anchor:'2026-10-15T00:00:00.000Z',actors:terms.actors.map(a=>({...a,percent:a.key==='fanasa'?'25':a.key==='provider'?'55':a.percent}))}}};await assert.rejects(store.economics.command(c.id,amendDraft),/تأیید/);for(const action of ['submit','approve']){changed=await store.reviewAmendment(c.id,amendment.id,{action,expectedStatus:amendment.status,expectedRevision:amendment.workflow.revision,idempotencyKey:randomUUID(),comment:'بررسی'});amendment=changed.amendments[0];}
  state=await store.economics.command(c.id,amendDraft);const amendSign={...sign,expectedRevision:state.revision,idempotencyKey:randomUUID(),payload:{...sign.payload,versionId:state.versions.at(-1).id}},before=structuredClone(state),transaction=db.transaction;db.transaction=work=>transaction(tx=>work({...tx,query:async(sql,args)=>{if(sql.startsWith('INSERT INTO contracts.contract_events'))throw Error('audit rollback');return tx.query(sql,args);}}));try{await assert.rejects(store.economics.command(c.id,amendSign),/audit rollback/);}finally{db.transaction=transaction;}assert.deepEqual(await store.economics.read(c.id),before);state=await store.economics.command(c.id,amendSign);assert.deepEqual(state.versions[0],v);assert.equal(state.current.id,v.id);assert.equal((await store.contract(c.id)).amendments[0].status,'approved');
  await command('prepare',{contractId:c.id,versionId:state.versions.at(-1).id,reference:'PROVIDER-READY'});assert.equal(application.status,'awaiting-central-provisioning');assert.equal(application.provisioned,false);
  assert.deepEqual((await store.economics.read(c.id)).versions[0],v);assert.deepEqual((await store.contract(c.id)).snapshot,c.snapshot);
 }finally{await db.close();}
});
