import test from 'node:test';
import assert from 'node:assert/strict';
import {renderExecutionDocument} from '../lib/execution-document.mjs';
function fixture(){
 const line={itemId:'item',title:'عنوان ثبت‌شده <script>bad()</script>',quantity:1000,unitPrice:4000,amount:4000};
 const invoice={id:'invoice',number:'INV-1',kind:'progress',milestoneId:'phase',lines:[line],gross:4000,tax:400,retention:400,withholding:100,insurance:50,penalty:50,advanceRecovery:0,net:3800,dueDate:'2026-12-01',reference:'صورتجلسه',basis:'مبنای واقعی',status:'disputed',decisions:[{action:'invoice-dispute',reference:'DISPUTE',comment:'اختلاف باز',at:'2026-10-10T01:00:00Z'}]};
 return {number:'C-EXPORT',title:'اجرای آزمون',customerName:'طرف آزمون',amount:99999999,execution:{status:'running',revision:18,basis:{reference:'SIGNED-REF',counterparties:'دو طرف',signedDate:'2026-10-01',startDate:'2026-10-01',endDate:'2027-10-01',amount:10000,advanceLimit:1000,direction:'payable'},effectiveAmount:10000,endDate:'2027-10-01',milestones:[{id:'phase',title:'مرحله',gross:10000,dueDate:'2026-12-01',condition:'پذیرش'}],items:[{id:'item',milestoneId:'phase',title:'عنوان جاری',quantity:2000,unit:'بسته',unitPrice:6000,owner:'مجری',criteria:'پذیرش',dueDate:'2026-11-01'}],deliveries:[{id:'delivery',itemId:'item',quantity:1000,status:'accepted',reference:'DEL',deliveredAt:'2026-10-10',review:{reference:'ACCEPT',comment:'پذیرش با مدرک'}}],invoices:[invoice,{...invoice,id:'cancelled',number:'INV-CANCEL',status:'cancelled'},{...invoice,id:'rejected',number:'INV-REJECT',status:'rejected'}],payments:[{id:'reversed',invoiceId:'invoice',amount:1000,paidAt:'2026-10-10',reference:'PAY-REVERSED',method:'حواله'},{id:'effective',invoiceId:'invoice',amount:800,paidAt:'2026-10-10',reference:'PAY-EFFECTIVE',method:'حواله'}],reversals:[{paymentId:'reversed',reference:'REV-REF',comment:'برگشت مستند',at:'2026-10-10T02:00:00Z'}],deductionSettlements:[{id:'tax-reversed',invoiceId:'invoice',kind:'withholding',amount:100,settledAt:'2026-10-10',reference:'TAX-OLD',recipient:'مالیات'},{id:'tax-effective',invoiceId:'invoice',kind:'withholding',amount:30,settledAt:'2026-10-10',reference:'TAX-NEW',recipient:'مالیات'}],deductionReversals:[{settlementId:'tax-reversed',reference:'TAX-REV',comment:'اصلاح رسید'}],obligations:[],guarantees:[{kind:'performance',amount:1000,reference:'GUARANTEE',issuer:'بانک',beneficiary:'کارفرما',expiryDate:'2027-01-01',condition:'تسویه',status:'held',extensions:[{from:'2026-12-01',to:'2027-01-01',reference:'EXTENSION',comment:'مجوز تمدید'}]}],issues:[],changes:[{reference:'CHANGE',reason:'تغییر نرخ آینده',before:{amount:10000,endDate:'2027-10-01'},after:{amount:10000,endDate:'2027-10-01'},itemChange:{itemId:'item',before:{quantity:2000,unitPrice:4000,dueDate:'2026-11-01'},after:{quantity:2000,unitPrice:6000,dueDate:'2026-11-01'}}}],history:[{revision:18,action:'change',actor:{name:'ثبت‌کننده'},at:'2026-10-10T01:00:00Z',payload:{reference:'CHANGE',comment:'</pre><script>bad()</script>'}}]}};
}
test('execution document preserves saved rates, reversals, disputed and excluded records',()=>{
 const c=fixture(),before=structuredClone(c),html=renderExecutionDocument(c,{generatedAt:'2026-10-10T03:00:00Z'});
 assert.match(html,/lang="fa" dir="rtl"/);assert.match(html,/مرکز رایان/);assert.match(html,/data:font\/woff2;base64/);
 assert.match(html,/SIGNED-REF/);assert.match(html,/پرداخت به طرف قرارداد/);assert.match(html,/INV-CANCEL/);assert.match(html,/INV-REJECT/);assert.match(html,/اختلاف مالی باز/);
 const active=html.split('data-invoice-id="invoice"')[1].split('</article>')[0];
 assert.match(active,/۴٬۰۰۰ ریال/);assert.doesNotMatch(active,/۶٬۰۰۰ ریال/);assert.match(active,/۳٬۰۰۰ ریال/);assert.match(active,/۷۰ ریال/);assert.match(active,/۸۰۰ ریال/);
 assert.match(html,/REV-REF/);assert.match(html,/TAX-REV/);assert.match(html,/برگشت‌خورده؛ خارج از جمع مؤثر/);assert.match(html,/EXTENSION/);
 assert.match(html,/&lt;script&gt;bad\(\)&lt;\/script&gt;/);assert.doesNotMatch(html,/<script|onerror=|۹۹٬۹۹۹٬۹۹۹/);assert.deepEqual(c,before);
});
test('execution report requires explicitly started execution',()=>{
 assert.throws(()=>renderExecutionDocument({number:'C',execution:null}),e=>e.status===409&&e.code==='execution_not_started');
});
