import {randomUUID} from 'node:crypto';
import {text,requireValue} from './domain.mjs';
import {serviceLimitHash} from './service-limits.mjs';
import {currentContractParameters} from './contract-parameters.mjs';
import {actorRoles,fundingSources,revenueBases,percentParts,allocateRevenue} from '../public/economy-model.js';
const check=(v,m,s=400)=>requireValue(v,m,s);
const instant=v=>{check(typeof v==='string'&&/^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d\.\d{3}Z$/.test(v)&&Number.isFinite(Date.parse(v))&&new Date(v).toISOString()===v,'زمان UTC معتبر لازم است.');return v;};
const amount=v=>{check(typeof v==='string'&&/^\d{1,16}$/.test(v)&&BigInt(v)<=BigInt(Number.MAX_SAFE_INTEGER),'مبلغ باید رشته صحیح ریالی باشد.');return BigInt(v).toString();};
const integer=(v,min,max,label)=>{check(Number.isSafeInteger(v)&&v>=min&&v<=max,label+' معتبر نیست.');return v;};
const actorData=a=>a?{id:a.id,subject:a.subject,name:a.name,email:a.email}:null;
export function settlementSchedule(versions,proposals=[],{now=Date.now(),executionStatus='running',limit=100}={}){
 if(executionStatus!=='running')return {periods:[],truncated:false,reason:'execution-not-running'};
 const signed=versions.filter(v=>v.status==='signed').sort((a,b)=>a.effectiveAt.localeCompare(b.effectiveAt)),existing=new Set(proposals.map(p=>p.periodStart+'|'+p.periodEnd)),periods=[];
 for(const [index,v]of signed.entries()){
  const duration=v.terms.periodDays*86400000,end=Math.min(Date.parse(v.validTo),signed[index+1]?Date.parse(signed[index+1].effectiveAt):Infinity,now-v.terms.holdDays*86400000);
  for(let start=Date.parse(v.terms.anchor);start+duration<=end;start+=duration){const periodStart=new Date(start).toISOString(),periodEnd=new Date(start+duration).toISOString();if(existing.has(periodStart+'|'+periodEnd))continue;if(periods.length===limit)return {periods,truncated:true};periods.push({versionId:v.id,periodStart,periodEnd,dueAt:new Date(start+duration+v.terms.holdDays*86400000).toISOString(),status:'awaiting-financial-evidence',customerCreditEnabled:v.terms.customerCredit.enabled});}
 }
 return {periods,truncated:false};
}
export function validateEconomicTerms(p){
 check(p&&typeof p==='object'&&!Array.isArray(p),'شرایط اقتصاد قرارداد لازم است.');
 const serviceKey=text(p.serviceKey,'کلید سرویس',{max:120});check(Array.isArray(p.actors)&&p.actors.length>=2&&p.actors.length<=30,'بین دو تا ۳۰ بازیگر لازم است.');
 const actors=p.actors.map(a=>{check(Object.hasOwn(actorRoles,a.role),'نقش بازیگر معتبر نیست.');const key=text(a.key,'کلید بازیگر',{max:64});check(/^[a-z][a-z0-9.-]*$/.test(key),'کلید بازیگر معتبر نیست.');let parts;try{parts=percentParts(a.percent);}catch(e){check(false,e.message);}check(parts>0,'سهم هر بازیگر باید مثبت باشد.');return {key,name:text(a.name,'نام بازیگر',{max:250}),role:a.role,percent:a.percent,agreementReference:text(a.agreementReference,'مرجع قرارداد بازیگر',{max:500})};});
 check(new Set(actors.map(a=>a.key)).size===actors.length&&actors.filter(a=>a.role==='infrastructure').length===1&&actors.some(a=>a.role==='provider'),'بازیگران یکتا، یک زیرساخت فن‌آسا و ارائه‌دهنده سرویس لازم‌اند.');try{allocateRevenue('0',actors);}catch(e){check(false,e.message);}
 check(Object.hasOwn(revenueBases,p.revenueBase),'مبنای سهم معتبر نیست.');
 const periodDays=integer(p.periodDays,1,90,'فاصله تسویه'),holdDays=integer(p.holdDays,0,90,'مهلت نگه‌داشت'),anchor=instant(p.anchor),minimumPayout=amount(p.minimumPayout);
 check(['hold-disputed','hold-all'].includes(p.disputePolicy),'سیاست اختلاف معتبر نیست.');
 const credit=p.customerCredit??{enabled:false};check(credit&&typeof credit.enabled==='boolean','وضعیت شارژ مشتری لازم است.');let customerCredit={enabled:false};
 if(credit.enabled){check(Object.hasOwn(fundingSources,credit.fundingSource),'منبع تأمین اعتبار لازم است.');customerCredit={enabled:true,fundingSource:credit.fundingSource,ceiling:amount(credit.ceiling),periodDays:integer(credit.periodDays,1,90,'دوره شارژ مشتری'),reference:text(credit.reference,'سند مبنای اعتبار مشتری',{max:500})};check(BigInt(customerCredit.ceiling)>0n,'سقف اعتبار باید مثبت باشد.');}
 return {serviceKey,actors,revenueBase:p.revenueBase,periodDays,holdDays,anchor,minimumPayout,disputePolicy:p.disputePolicy,customerCredit,currency:'IRR'};
}
export function economicAllocation(terms,p){
 const collected=BigInt(amount(p.collected)),refunds=BigInt(amount(p.refunds)),tax=BigInt(amount(p.tax)),disputed=BigInt(amount(p.disputed));check(refunds+tax+disputed<=collected,'کسورات از دریافت بیشتر است.');
 const base=collected-refunds-(terms.revenueBase==='net_collected'?tax:0n),hold=terms.disputePolicy==='hold-all'&&disputed>0n?base:disputed;
 check(hold<=base,'مبلغ اختلاف از مبنای سهم بیشتر است.');const distributable=base-hold;
 const allocations=allocateRevenue(distributable.toString(),terms.actors).map(a=>({...a,disposition:BigInt(a.amount)<BigInt(terms.minimumPayout)?'carry-forward':'request-central-credit'}));
 return {collected:collected.toString(),refunds:refunds.toString(),tax:tax.toString(),disputed:disputed.toString(),distributionBase:base.toString(),held:hold.toString(),distributable:distributable.toString(),allocations,balanced:allocations.reduce((s,a)=>s+BigInt(a.amount),0n)+hold===base};
}
export function createDigitalEconomyStore(db,tenantId){
 const authorize=(actor,action)=>{check(!actor||actor.tenantId===tenantId,'تننت مجاز نیست.',403);const roles=actor?.roles||['contract_admin'];check(roles.some(r=>['contract_admin','platform_admin'].includes(r))||(action==='sign'?roles.includes('legal_reviewer'):action==='settlement'?roles.includes('finance_reviewer'):roles.includes('account_manager')),'نقش شما اجازه این اقدام را ندارد.',403);};
 async function contract(tx,id){const c=(await tx.query('SELECT * FROM contracts.contracts WHERE tenant_id=$1 AND id=$2 FOR UPDATE',[tenantId,id])).rows[0];check(c,'قرارداد یافت نشد.',404);return c;}
 async function source(tx,c,kind,amendmentId){check(['contract','amendment'].includes(kind),'منبع معتبر نیست.');if(kind==='amendment'){const a=(await tx.query('SELECT * FROM contracts.contract_amendments WHERE tenant_id=$1 AND contract_id=$2 AND id=$3',[tenantId,c.id,amendmentId])).rows[0];check(a,'الحاقیه یافت نشد.',404);return {document:a.summary||'',status:a.status,id:a.id};}const d=(await tx.query("SELECT metadata FROM contracts.contract_documents WHERE tenant_id=$1 AND contract_id=$2 AND document_type='proposal_revision' ORDER BY version_no DESC,uploaded_at DESC LIMIT 1",[tenantId,c.id])).rows[0];return {document:d?.metadata?.body||c.template_snapshot?.document||'',status:c.status,id:c.id};}
 async function read(id){
  check((await db.query('SELECT id FROM contracts.contracts WHERE tenant_id=$1 AND id=$2',[tenantId,id])).rows[0],'قرارداد یافت نشد.',404);
  const r=(await db.query('SELECT revision,state FROM contracts.contract_economics WHERE tenant_id=$1 AND contract_id=$2',[tenantId,id])).rows[0],execution=(await db.query('SELECT state FROM contracts.contract_execution WHERE tenant_id=$1 AND contract_id=$2',[tenantId,id])).rows[0]?.state;
  const settlements=(await db.query('SELECT id,proposal FROM contracts.settlement_proposals WHERE tenant_id=$1 AND contract_id=$2 ORDER BY period_start DESC',[tenantId,id])).rows,executionStatus=execution?.status||'not-started',versions=r?.state.versions||[];
  return {revision:r?.revision||0,versions,current:currentContractParameters(r?.state,{executionStatus}),executionStatus,settlements,schedule:settlementSchedule(versions,settlements.map(s=>s.proposal),{executionStatus}),accountingStatus:'awaiting-central-accounting',walletPosted:false};
 }
 async function command(id,input,actor=null){
  check(input&&['draft','sign','cancel'].includes(input.action),'اقدام اقتصاد قرارداد معتبر نیست.');authorize(actor,input.action);check(Number.isSafeInteger(input.expectedRevision)&&input.expectedRevision>=0,'نسخه مورد انتظار لازم است.');const p=input.payload;check(p&&typeof p==='object','محتوای اقدام لازم است.');const requestKey=text(input.idempotencyKey,'کلید درخواست',{max:120}),who=actorData(actor),hash=serviceLimitHash({action:input.action,payload:p,expectedRevision:input.expectedRevision,subject:who?.subject||null});
  await db.transaction(async tx=>{const c=await contract(tx,id),receipt=(await tx.query('SELECT request_hash FROM contracts.economics_commands WHERE tenant_id=$1 AND contract_id=$2 AND request_key=$3',[tenantId,id,requestKey])).rows[0];if(receipt){check(receipt.request_hash===hash,'کلید درخواست با محتوای دیگر استفاده شده است.',409);return;}const row=(await tx.query('SELECT * FROM contracts.contract_economics WHERE tenant_id=$1 AND contract_id=$2 FOR UPDATE',[tenantId,id])).rows[0];check((row?.revision||0)===input.expectedRevision,'اقتصاد قرارداد تغییر کرده است.',409);const state=row?.state||{versions:[]},revision=(row?.revision||0)+1,at=new Date().toISOString();let event=null;
   if(input.action==='draft'){
    check(!state.versions.some(v=>v.status==='draft'),'پیش‌نویس باز را تعیین تکلیف کنید.',409);const terms=validateEconomicTerms(p.terms),validFrom=instant(p.validFrom),validTo=instant(p.validTo),effectiveAt=instant(p.effectiveAt);check(validFrom<validTo&&validFrom<=effectiveAt&&effectiveAt<validTo&&terms.anchor>=effectiveAt&&terms.anchor<validTo,'بازه قرارداد و مبدأ تسویه معتبر نیست.');
    const s=await source(tx,c,p.sourceKind,p.amendmentId);check(s.document.length>0&&p.sourceHash===serviceLimitHash(s.document),'منبع قرارداد تغییر کرده یا خالی است.',409);const clauseQuote=text(p.clauseQuote,'بند دقیق اقتصاد قرارداد',{max:12000});check(s.document.includes(clauseQuote),'بند در منبع یافت نشد.');if(p.sourceKind==='amendment')check(['approved','signed'].includes(s.status),'الحاقیه باید تأیید یا امضا شده باشد.',409);const prior=state.versions.filter(v=>v.status==='signed').at(-1);check(!prior||p.sourceKind==='amendment'&&s.id!==prior.source.id&&effectiveAt>prior.effectiveAt,'اصلاح سهم‌ها باید با الحاقیه تازه و زمان اثر بعدی باشد.',409);
    state.versions.push({id:randomUUID(),version:state.versions.length+1,status:'draft',terms,validFrom,validTo,effectiveAt,source:{kind:p.sourceKind,id:s.id,sha256:p.sourceHash,clauseQuote},createdAt:at,createdBy:who});
   }else{const v=state.versions.find(v=>v.id===p.versionId);check(v?.status==='draft','پیش‌نویس قابل اقدام یافت نشد.',409);if(input.action==='cancel'){v.status='cancelled';v.cancellation={reference:text(p.reference,'مرجع لغو',{max:500}),comment:text(p.comment,'علت لغو',{max:2000}),at,actor:who};}else{
    const execution=(await tx.query('SELECT state FROM contracts.contract_execution WHERE tenant_id=$1 AND contract_id=$2',[tenantId,id])).rows[0]?.state;check(execution?.status==='running','مبنای امضاشده و اجرای فعال لازم است.',409);check(p.confirmSigned===true,'تأیید امضای طرفین لازم است.');const s=await source(tx,c,v.source.kind,v.source.id);check(serviceLimitHash(s.document)===v.source.sha256&&(v.source.kind!=='amendment'||['approved','signed'].includes(s.status)),'منبع پیش‌نویس تغییر کرده است.',409);
    const day=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tehran',year:'numeric',month:'2-digit',day:'2-digit'}),signedDate=p.signedDate;check(typeof signedDate==='string'&&/^\d{4}-\d\d-\d\d$/.test(signedDate)&&Number.isFinite(Date.parse(signedDate+'T00:00:00Z'))&&new Date(signedDate+'T00:00:00Z').toISOString().slice(0,10)===signedDate&&signedDate<=day.format(new Date(at))&&signedDate<=day.format(new Date(v.effectiveAt)),'تاریخ امضا معتبر نیست.');const begin=new Date(execution.basis.startDate+'T00:00:00+03:30').toISOString(),end=new Date(+new Date(execution.endDate+'T00:00:00+03:30')+86400000).toISOString();check(v.validFrom>=begin&&v.validTo<=end,'بازه باید داخل قرارداد امضاشده باشد.');v.signature={reference:text(p.reference,'مرجع امضا',{max:500}),counterparties:text(p.counterparties,'امضاکنندگان',{max:1000}),signedDate,recordedAt:at,actor:who};v.status='signed';event={schemaVersion:'1.0.0',eventType:'contract.economics.signed',eventId:'nce-'+randomUUID(),producer:'fanasa-contracts',localTenantId:tenantId,contractId:id,versionId:v.id,aggregateVersion:revision,effectiveAt:v.effectiveAt,occurredAt:at,version:structuredClone(v)};
   }}
   if(row)await tx.query('UPDATE contracts.contract_economics SET revision=$3,state=$4,updated_at=now() WHERE tenant_id=$1 AND contract_id=$2',[tenantId,id,revision,JSON.stringify(state)]);else await tx.query('INSERT INTO contracts.contract_economics(tenant_id,contract_id,revision,state) VALUES($1,$2,$3,$4)',[tenantId,id,revision,JSON.stringify(state)]);
   await tx.query('INSERT INTO contracts.economics_commands(tenant_id,contract_id,request_key,request_hash,revision,action,payload,actor) VALUES($1,$2,$3,$4,$5,$6,$7,$8)',[tenantId,id,requestKey,hash,revision,input.action,JSON.stringify(p),JSON.stringify(who)]);
   if(event)await tx.query('INSERT INTO contracts.economics_outbox(event_id,tenant_id,contract_id,version_id,aggregate_version,effective_at,payload,payload_sha256) VALUES($1,$2,$3,$4,$5,$6,$7,$8)',[event.eventId,tenantId,id,event.versionId,revision,event.effectiveAt,JSON.stringify(event),serviceLimitHash(event)]);
   await tx.query('INSERT INTO contracts.contract_events(tenant_id,contract_id,event_type,actor_label,payload) VALUES($1,$2,$3,$4,$5)',[tenantId,id,'economics_updated',who?.name||'آزمون محلی',JSON.stringify({action:input.action,revision,actor:who,eventId:event?.eventId||null})]);
  });return read(id);
 }
 async function proposeSettlement(id,input,actor=null){authorize(actor,'settlement');const requestKey=text(input.idempotencyKey,'کلید درخواست',{max:120}),hash=serviceLimitHash({input,subject:actor?.subject||null});await db.transaction(async tx=>{await contract(tx,id);const old=(await tx.query('SELECT request_hash FROM contracts.settlement_proposals WHERE tenant_id=$1 AND request_key=$2',[tenantId,requestKey])).rows[0];if(old){check(old.request_hash===hash,'کلید درخواست با محتوای دیگر استفاده شده است.',409);return;}
  const row=(await tx.query('SELECT revision,state FROM contracts.contract_economics WHERE tenant_id=$1 AND contract_id=$2',[tenantId,id])).rows[0];check(row&&row.revision===input.expectedRevision,'نسخه اقتصاد قرارداد تغییر کرده است.',409);const v=row.state.versions.find(v=>v.id===input.versionId&&v.status==='signed');check(v,'نسخه امضاشده یافت نشد.',409);const execution=(await tx.query('SELECT state FROM contracts.contract_execution WHERE tenant_id=$1 AND contract_id=$2',[tenantId,id])).rows[0]?.state;check(execution?.status==='running','اجرای قرارداد متوقف یا بسته است.',409);
  const from=instant(input.periodStart),to=instant(input.periodEnd),period=v.terms.periodDays*86400000;check(from>=v.terms.anchor&&from>=v.validFrom&&from>=v.effectiveAt&&to<=v.validTo&&Date.parse(to)-Date.parse(from)===period&&(Date.parse(from)-Date.parse(v.terms.anchor))%period===0&&Date.parse(to)+v.terms.holdDays*86400000<=Date.now(),'دوره تسویه بسته‌شده با مبدأ و مهلت قرارداد لازم است.');check(!row.state.versions.some(n=>n.status==='signed'&&n.effectiveAt>v.effectiveAt&&n.effectiveAt<to),'دوره از مرز اصلاحیه عبور می‌کند؛ نیازمند تفکیک توسط حسابداری مرکزی است.',409);
  check(input.confirmEvidence===true,'تأیید مدارک مبنای مالی لازم است.');const evidenceReference=text(input.evidenceReference,'مرجع گزارش مالی',{max:1000}),allocation=economicAllocation(v.terms,input),proposal={id:randomUUID(),contractId:id,versionId:v.id,periodStart:from,periodEnd:to,dueAt:new Date(Date.parse(to)+v.terms.holdDays*86400000).toISOString(),evidenceReference,evidenceStatus:'operator-reviewed-not-central-verified',terms:structuredClone(v.terms),allocation,customerCreditInstruction:v.terms.customerCredit.enabled?{...v.terms.customerCredit,status:'awaiting-funding-evidence-and-central-approval'}:null,createdAt:new Date().toISOString(),actor:actorData(actor),status:'awaiting-central-accounting',walletPosted:false};
  await tx.query('INSERT INTO contracts.settlement_proposals(id,tenant_id,contract_id,version_id,period_start,period_end,proposal,request_key,request_hash) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)',[proposal.id,tenantId,id,v.id,from,to,JSON.stringify(proposal),requestKey,hash]);await tx.query('INSERT INTO contracts.contract_events(tenant_id,contract_id,event_type,actor_label,payload) VALUES($1,$2,$3,$4,$5)',[tenantId,id,'settlement_proposed',actor?.name||'آزمون محلی',JSON.stringify({proposalId:proposal.id,actor:actorData(actor)})]);
 });return read(id);}
 async function sourceDocument(id,input={}){let result;await db.transaction(async tx=>{const c=await contract(tx,id),s=await source(tx,c,input.sourceKind||'contract',input.amendmentId);result={source:{kind:input.sourceKind||'contract',id:s.id,status:s.status,sha256:serviceLimitHash(s.document)},document:s.document};});return result;}
 return {read,command,proposeSettlement,sourceDocument};
}
