import { randomUUID, createHash } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { AppError, requireValue, text } from './domain.mjs';

export function createIntegrations(store,{neoConfig,fetchImpl=fetch,fetchCatalog}={}){
  const locks=new Map();
  const serial=async(key,fn)=>{const previous=locks.get(key)||Promise.resolve();let release;const lock=new Promise(r=>release=r);locks.set(key,lock);await previous;try{return await fn();}finally{release();if(locks.get(key)===lock)locks.delete(key);}};
  async function config(){return neoConfig||JSON.parse(await readFile(new URL('../planning/neo-binding.json',import.meta.url),'utf8'));}
  async function neo(path,body){const c=await config();const url=new URL(c.apiBaseUrl);const loopback=['localhost','127.0.0.1','[::1]'].includes(url.hostname);requireValue(url.protocol==='https:'||(loopback&&url.protocol==='http:'),'آدرس اتصال Neo معتبر نیست.');const token=process.env.NEO_API_TOKEN;const headers={'Content-Type':'application/json','X-Orchestration-Chat':process.env.CODEX_THREAD_ID||'neocontract-demo'};if(token)headers.Authorization=`Bearer ${token}`;else if(loopback)headers['X-Orchestration-Local']='true';else throw new AppError('توکن اتصال Neo تنظیم نشده است.',503);const r=await fetchImpl(`${c.apiBaseUrl.replace(/\/$/,'')}/api/orchestration/v1/organizations/${c.organizationId}/workspaces/${c.workspaceId}${path}`,{method:body===undefined?'GET':'POST',headers,...(body===undefined?{}:{body:JSON.stringify(body)}),redirect:'error',signal:AbortSignal.timeout(15000)});if(!r.ok)throw new AppError(`Neo پاسخ ${r.status} داد؛ دوباره تلاش کنید.`,502,'neo_unavailable');return r.json();}
  async function neoHealth(){try{const c=await config();const cat=await neo('/catalog');const project=cat.projects.find(p=>p.id===c.projectId);requireValue(project,'پروژه اتصال Neo یافت نشد.',502);return {status:'connected',project:project.name,projectId:project.id,url:c.webBaseUrl,checkedAt:new Date().toISOString()};}catch(e){return {status:'unavailable',message:e.message,checkedAt:new Date().toISOString()};}}
  async function allNeoItems(){const c=await config();const result=[];for(let skip=0;skip<10000;skip+=200){const page=await neo(`/items?projectId=${c.projectId}&includeArchived=true&take=200&skip=${skip}`);result.push(...page.items);if(skip+page.items.length>=page.total)return result;}throw new AppError('برد Neo بیش از محدوده صفحه‌بندی است.',502);}
  async function syncContract(id){return serial(`neo:${id}`,async()=>{
    const contract=await store.contract(id);const cfg=await config();const jobId=randomUUID();await store.q("INSERT INTO contracts.integration_jobs(id,tenant_id,contract_id,kind,status,attempts,payload) VALUES($1,$2,$3,'neo-contract','running',1,$4)",[jobId,store.tenantId,id,JSON.stringify({contractId:id})]);
    try{
      const all=await allNeoItems();const prefix=`NC-${id.replaceAll('-','').slice(0,16).toUpperCase()}`;
      async function ensure(key,title,description,parentWorkItemId){let item=all.find(x=>x.key===key);if(!item){try{const d=await neo('/items',{projectId:cfg.projectId,key,title,domain:'neocontract-demo',description,priority:'Normal',parentWorkItemId:parentWorkItemId||null});item=d.item;all.push(item);}catch(e){const refreshed=await allNeoItems();item=refreshed.find(x=>x.key===key);if(!item)throw e;}}requireValue(item.domain==='neocontract-demo' && item.parentWorkItemId===(parentWorkItemId||null),'کلید کار Neo به زمینه دیگری تعلق دارد.',409);requireValue(!item.ownerAgentId || (item.ownerAgentId==='local-web' && item.ownerChatId===(process.env.CODEX_THREAD_ID||'neocontract-demo')),'کار Neo به چت دیگری تخصیص دارد.',409);return item;}
      const parent=await ensure(prefix,`${contract.number} — ${contract.title}`,`قرارداد نمایشی NeoContract. شناسه: ${id}. مشتری: ${contract.customerName}. متن قرارداد در سامانه نگهداری می‌شود.`);
      const stages=[];let previous=null;
      for(const [index,s] of contract.stages.filter(x=>x.enabled).entries()){
        const item=await ensure(`${prefix}-S${index+1}`,s.name,`مرحله قرارداد ${contract.number}؛ نقش ${s.role}؛ مهلت ${s.slaDays} روز. شناسه مرحله: ${s.id}`,parent.id);
        let d=await neo(`/items/${item.id}`);
        if(previous&&!d.dependencies.includes(previous)&&['Backlog','Ready','Blocked'].includes(d.item.status))d=await neo(`/items/${item.id}/dependencies`,{expectedVersion:d.item.version,dependsOnWorkItemId:previous});
        const message=`وضعیت مرحله در NeoContract: ${s.status}؛ قرارداد ${contract.number}.`;
        if(!d.logs.some(x=>x.message===message)&&(!d.item.ownerAgentId||(d.item.ownerAgentId==='local-web'&&d.item.ownerChatId===(process.env.CODEX_THREAD_ID||'neocontract-demo'))))d=await neo(`/items/${item.id}/logs`,{expectedVersion:d.item.version,message});
        stages.push({stageId:s.id,itemId:item.id,key:item.key,status:d.item.status});previous=item.id;
      }
      const result={organizationId:cfg.organizationId,workspaceId:cfg.workspaceId,projectId:cfg.projectId,parentItemId:parent.id,key:prefix,stages,url:cfg.webBaseUrl,syncedAt:new Date().toISOString(),status:'synced'};
      await store.db.transaction(async tx=>{await tx.query('UPDATE contracts.contracts SET neo_binding=$3 WHERE tenant_id=$1 AND id=$2',[store.tenantId,id,JSON.stringify(result)]);await tx.query("UPDATE contracts.integration_jobs SET status='succeeded',result=$3 WHERE tenant_id=$1 AND id=$2",[store.tenantId,jobId,JSON.stringify(result)]);});return result;
    }catch(e){await store.q("UPDATE contracts.integration_jobs SET status='failed',error_message=$3,next_attempt_at=now()+interval '1 minute' WHERE tenant_id=$1 AND id=$2",[store.tenantId,jobId,e.message]);throw e;}
  });}
  async function imports(){const rows=await store.q('SELECT id,status,source_url,content_sha256,http_status,error_message,created_at,reviewed_at,payload FROM contracts.catalog_imports WHERE tenant_id=$1 ORDER BY created_at DESC LIMIT 20',[store.tenantId]);return rows.map(r=>({id:r.id,importId:r.id,status:r.status,url:r.source_url,sha256:r.content_sha256,httpStatus:r.http_status,error:r.error_message,createdAt:r.created_at,reviewedAt:r.reviewed_at,counts:r.payload?.catalog?{centers:r.payload.catalog.centers.length,services:r.payload.catalog.services.length}:null,sources:r.payload?.sources||[],warnings:r.payload?.warnings||[]}));}
  async function runImport(){return serial('fanasa-import',async()=>{
    const id=randomUUID();await store.q("INSERT INTO contracts.catalog_imports(id,tenant_id,source_url,status) VALUES($1,$2,'https://fanasa.net/fa/products','pending')",[id,store.tenantId]);
    try{const provider=fetchCatalog||(await import('./fanasa-importer.mjs')).fetchFanasaCatalog;const report=await provider();requireValue(report.catalog?.services?.length===87&&report.catalog?.centers?.length===14,'برداشت منبع کامل نیست؛ کاتالوگ قبلی حفظ شد.',502);const hash=createHash('sha256').update(JSON.stringify(report)).digest('hex');await store.q('UPDATE contracts.catalog_imports SET payload=$3,content_sha256=$4,http_status=200 WHERE tenant_id=$1 AND id=$2',[store.tenantId,id,JSON.stringify(report),hash]);return (await imports()).find(x=>x.id===id);}catch(e){await store.q("UPDATE contracts.catalog_imports SET status='failed',error_message=$3 WHERE tenant_id=$1 AND id=$2",[store.tenantId,id,e.message]);throw new AppError(`دریافت منبع ناموفق بود؛ نسخه قبلی حفظ شد. ${e.message}`,502);}
  });}
  async function approveImport(id){const row=await store.one('SELECT * FROM contracts.catalog_imports WHERE tenant_id=$1 AND id=$2',[store.tenantId,id]);requireValue(row&&['pending','approved'].includes(row.status)&&row.payload?.catalog,'برداشت آماده انتشار یافت نشد.');if(row.status==='approved')return (await imports()).find(x=>x.id===id);
    const catalog=row.payload.catalog;catalog.verificationStatus='http-observed-unverified';catalog.reviewedAt=new Date().toISOString();catalog.importId=id;
    const codes=new Set(catalog.services.map(x=>x.code));requireValue(codes.size===87&&catalog.centers.length===14,'شمارش سرویس‌های برداشت معتبر نیست.');
    await store.db.transaction(async tx=>{
      for(const s of catalog.services){const r=(await tx.query('SELECT id FROM contracts.catalog_services WHERE tenant_id=$1 AND service_code=$2',[store.tenantId,s.code])).rows[0];requireValue(r,'سرویس برداشت‌شده با کاتالوگ محلی تطبیق ندارد.');await tx.query("UPDATE contracts.catalog_services SET name=$3,pricing_model=$4,delivery=$5,status='active',verification_status='http-observed-unverified',metadata=$6 WHERE tenant_id=$1 AND id=$2",[store.tenantId,r.id,s.name,s.model||s.revenueModel,s.delivery,JSON.stringify(s)]);const tier=(await tx.query('SELECT id FROM contracts.sla_tiers WHERE tenant_id=$1 AND code=$2',[store.tenantId,s.tier])).rows[0];if(tier){await tx.query('UPDATE contracts.catalog_service_sla SET is_default=false WHERE tenant_id=$1 AND service_id=$2',[store.tenantId,r.id]);await tx.query("INSERT INTO contracts.catalog_service_sla(tenant_id,service_id,sla_tier_id,is_default,verification_status,metadata) VALUES($1,$2,$3,true,'http-observed-unverified',$4) ON CONFLICT(tenant_id,service_id,sla_tier_id) DO UPDATE SET is_default=true,verification_status=excluded.verification_status,metadata=excluded.metadata",[store.tenantId,r.id,tier.id,JSON.stringify({sourceUrl:s.sourceUrl,sourceHash:s.sourceHash,importId:id})]);}}
      await tx.query('INSERT INTO contracts.app_settings(tenant_id,key,value) VALUES($1,$2,$3) ON CONFLICT(tenant_id,key) DO UPDATE SET value=excluded.value',[store.tenantId,'catalog-current',JSON.stringify(catalog)]);
      await tx.query("UPDATE contracts.catalog_imports SET status='approved',reviewed_at=now() WHERE tenant_id=$1 AND id=$2",[store.tenantId,id]);
    });return (await imports()).find(x=>x.id===id);
  }
  async function status(){const source=await store.catalog();return {neo:await neoHealth(),sync:{source:source.source,observedAt:source.observedAt,verificationStatus:source.verificationStatus,operatorReview:source.operatorReview,imports:await imports()},database:await store.db.health()};}
  return {status,neoHealth,syncContract,runImport,approveImport,imports};
}
