/* NeoContract SQL Server schema. Execute with sqlcmd or scripts/sqlserver-provision.ps1. */
IF DB_ID(N'NeoContract') IS NULL CREATE DATABASE [NeoContract];
GO
USE [NeoContract];
GO
IF SCHEMA_ID(N'contracts') IS NULL EXEC(N'CREATE SCHEMA [contracts]');
GO
IF OBJECT_ID(N'contracts.schema_migrations',N'U') IS NULL CREATE TABLE contracts.schema_migrations(
 version int NOT NULL CONSTRAINT PK_schema_migrations PRIMARY KEY,name nvarchar(255) NOT NULL,checksum nvarchar(100) NOT NULL,applied_at datetime2(3) NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID(N'contracts.tenants',N'U') IS NULL CREATE TABLE contracts.tenants(
 id uniqueidentifier NOT NULL CONSTRAINT PK_tenants PRIMARY KEY,slug nvarchar(100) NOT NULL,name nvarchar(250) NOT NULL,status nvarchar(20) NOT NULL DEFAULT N'active',settings nvarchar(max) NOT NULL DEFAULT N'{}',created_at datetime2(3) NOT NULL DEFAULT SYSUTCDATETIME(),updated_at datetime2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT UQ_tenants_slug UNIQUE(slug));
IF OBJECT_ID(N'contracts.account_managers',N'U') IS NULL CREATE TABLE contracts.account_managers(
 id uniqueidentifier NOT NULL CONSTRAINT PK_account_managers PRIMARY KEY,tenant_id uniqueidentifier NOT NULL,manager_code nvarchar(100) NOT NULL,display_name nvarchar(250) NOT NULL,email nvarchar(320),phone nvarchar(80),portfolio nvarchar(250),status nvarchar(20) NOT NULL DEFAULT N'active',verification_status nvarchar(80) NOT NULL DEFAULT N'manual-unverified',metadata nvarchar(max) NOT NULL DEFAULT N'{}',created_at datetime2(3) NOT NULL DEFAULT SYSUTCDATETIME(),updated_at datetime2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT UQ_account_managers_code UNIQUE(tenant_id,manager_code),CONSTRAINT UQ_account_managers_tenant_id UNIQUE(tenant_id,id),CONSTRAINT FK_account_managers_tenant FOREIGN KEY(tenant_id) REFERENCES contracts.tenants(id));
IF OBJECT_ID(N'contracts.customers',N'U') IS NULL CREATE TABLE contracts.customers(
 id uniqueidentifier NOT NULL CONSTRAINT PK_customers PRIMARY KEY,tenant_id uniqueidentifier NOT NULL,customer_code nvarchar(100) NOT NULL,legal_name nvarchar(300) NOT NULL,parent_id uniqueidentifier,account_manager_id uniqueidentifier,unit nvarchar(250),industry nvarchar(250),segment nvarchar(100),status nvarchar(20) NOT NULL DEFAULT N'active',primary_contact_name nvarchar(250),primary_contact_email nvarchar(320),verification_status nvarchar(80) NOT NULL DEFAULT N'manual-unverified',metadata nvarchar(max) NOT NULL DEFAULT N'{}',created_at datetime2(3) NOT NULL DEFAULT SYSUTCDATETIME(),updated_at datetime2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT UQ_customers_code UNIQUE(tenant_id,customer_code),CONSTRAINT FK_customers_tenant FOREIGN KEY(tenant_id) REFERENCES contracts.tenants(id),CONSTRAINT FK_customers_manager FOREIGN KEY(tenant_id,account_manager_id) REFERENCES contracts.account_managers(tenant_id,id),CONSTRAINT FK_customers_parent FOREIGN KEY(parent_id) REFERENCES contracts.customers(id));
IF OBJECT_ID(N'contracts.contract_templates',N'U') IS NULL CREATE TABLE contracts.contract_templates(
 id uniqueidentifier NOT NULL CONSTRAINT PK_contract_templates PRIMARY KEY,tenant_id uniqueidentifier NOT NULL,code nvarchar(100) NOT NULL,name nvarchar(300) NOT NULL,category nvarchar(150),description nvarchar(max),status nvarchar(20) NOT NULL DEFAULT N'draft',current_version_id uniqueidentifier,metadata nvarchar(max) NOT NULL DEFAULT N'{}',created_at datetime2(3) NOT NULL DEFAULT SYSUTCDATETIME(),updated_at datetime2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT UQ_templates_code UNIQUE(tenant_id,code),CONSTRAINT FK_templates_tenant FOREIGN KEY(tenant_id) REFERENCES contracts.tenants(id));
IF OBJECT_ID(N'contracts.contract_template_versions',N'U') IS NULL CREATE TABLE contracts.contract_template_versions(
 id uniqueidentifier NOT NULL CONSTRAINT PK_template_versions PRIMARY KEY,tenant_id uniqueidentifier NOT NULL,template_id uniqueidentifier NOT NULL,version_no int NOT NULL,body_template nvarchar(max) NOT NULL DEFAULT N'',variable_schema nvarchar(max) NOT NULL DEFAULT N'{}',process_config nvarchar(max) NOT NULL DEFAULT N'{}',status nvarchar(20) NOT NULL DEFAULT N'draft',published_at datetime2(3),created_at datetime2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT UQ_template_versions UNIQUE(tenant_id,template_id,version_no),CONSTRAINT FK_template_versions_tenant FOREIGN KEY(tenant_id) REFERENCES contracts.tenants(id),CONSTRAINT FK_template_versions_template FOREIGN KEY(template_id) REFERENCES contracts.contract_templates(id));
IF OBJECT_ID(N'contracts.template_workflow_stages',N'U') IS NULL CREATE TABLE contracts.template_workflow_stages(
 id uniqueidentifier NOT NULL CONSTRAINT PK_template_stages PRIMARY KEY,tenant_id uniqueidentifier NOT NULL,template_version_id uniqueidentifier NOT NULL,stage_key nvarchar(120) NOT NULL,name nvarchar(250) NOT NULL,sequence_no int NOT NULL,required bit NOT NULL DEFAULT 1,role_key nvarchar(120),sla_days int,metadata nvarchar(max) NOT NULL DEFAULT N'{}',CONSTRAINT UQ_template_stages_key UNIQUE(tenant_id,template_version_id,stage_key),CONSTRAINT FK_template_stages_tenant FOREIGN KEY(tenant_id) REFERENCES contracts.tenants(id),CONSTRAINT FK_template_stages_version FOREIGN KEY(template_version_id) REFERENCES contracts.contract_template_versions(id));
IF OBJECT_ID(N'contracts.contracts',N'U') IS NULL CREATE TABLE contracts.contracts(
 id uniqueidentifier NOT NULL CONSTRAINT PK_contracts PRIMARY KEY,tenant_id uniqueidentifier NOT NULL,contract_no nvarchar(120) NOT NULL,title nvarchar(500) NOT NULL,contract_type nvarchar(150),status nvarchar(30) NOT NULL DEFAULT N'draft',template_version_id uniqueidentifier NOT NULL,customer_id uniqueidentifier,account_manager_id uniqueidentifier,template_snapshot nvarchar(max) NOT NULL DEFAULT N'{}',start_date date,end_date date,currency char(3) NOT NULL DEFAULT 'IRR',total_value decimal(20,4),variables nvarchar(max) NOT NULL DEFAULT N'{}',neo_binding nvarchar(max) NOT NULL DEFAULT N'{}',metadata nvarchar(max) NOT NULL DEFAULT N'{}',created_at datetime2(3) NOT NULL DEFAULT SYSUTCDATETIME(),updated_at datetime2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT UQ_contracts_no UNIQUE(tenant_id,contract_no),CONSTRAINT FK_contracts_tenant FOREIGN KEY(tenant_id) REFERENCES contracts.tenants(id),CONSTRAINT FK_contracts_version FOREIGN KEY(template_version_id) REFERENCES contracts.contract_template_versions(id),CONSTRAINT FK_contracts_customer FOREIGN KEY(customer_id) REFERENCES contracts.customers(id),CONSTRAINT FK_contracts_manager FOREIGN KEY(account_manager_id) REFERENCES contracts.account_managers(id),CONSTRAINT CK_contracts_dates CHECK(end_date IS NULL OR start_date IS NULL OR end_date>=start_date));
IF OBJECT_ID(N'contracts.contract_processes',N'U') IS NULL CREATE TABLE contracts.contract_processes(
 id uniqueidentifier NOT NULL CONSTRAINT PK_contract_processes PRIMARY KEY,tenant_id uniqueidentifier NOT NULL,contract_id uniqueidentifier NOT NULL,template_version_id uniqueidentifier NOT NULL,status nvarchar(20) NOT NULL DEFAULT N'pending',process_snapshot nvarchar(max) NOT NULL DEFAULT N'{}',started_at datetime2(3),completed_at datetime2(3),created_at datetime2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT UQ_processes_contract UNIQUE(tenant_id,contract_id),CONSTRAINT FK_processes_tenant FOREIGN KEY(tenant_id) REFERENCES contracts.tenants(id),CONSTRAINT FK_processes_contract FOREIGN KEY(contract_id) REFERENCES contracts.contracts(id));
IF OBJECT_ID(N'contracts.contract_process_steps',N'U') IS NULL CREATE TABLE contracts.contract_process_steps(
 id uniqueidentifier NOT NULL CONSTRAINT PK_process_steps PRIMARY KEY,tenant_id uniqueidentifier NOT NULL,process_id uniqueidentifier NOT NULL,step_key nvarchar(120) NOT NULL,name nvarchar(250) NOT NULL,sequence_no int NOT NULL,status nvarchar(20) NOT NULL DEFAULT N'pending',required bit NOT NULL DEFAULT 1,role_key nvarchar(120),sla_days int,started_at datetime2(3),completed_at datetime2(3),output_data nvarchar(max) NOT NULL DEFAULT N'{}',metadata nvarchar(max) NOT NULL DEFAULT N'{}',CONSTRAINT UQ_process_steps_key UNIQUE(tenant_id,process_id,step_key),CONSTRAINT FK_process_steps_tenant FOREIGN KEY(tenant_id) REFERENCES contracts.tenants(id),CONSTRAINT FK_process_steps_process FOREIGN KEY(process_id) REFERENCES contracts.contract_processes(id));
IF OBJECT_ID(N'contracts.contract_events',N'U') IS NULL CREATE TABLE contracts.contract_events(
 id uniqueidentifier NOT NULL CONSTRAINT PK_contract_events PRIMARY KEY,tenant_id uniqueidentifier NOT NULL,contract_id uniqueidentifier,event_type nvarchar(100) NOT NULL,from_status nvarchar(30),to_status nvarchar(30),actor_label nvarchar(250),payload nvarchar(max) NOT NULL DEFAULT N'{}',occurred_at datetime2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT FK_contract_events_tenant FOREIGN KEY(tenant_id) REFERENCES contracts.tenants(id),CONSTRAINT FK_contract_events_contract FOREIGN KEY(contract_id) REFERENCES contracts.contracts(id));
IF OBJECT_ID(N'contracts.app_settings',N'U') IS NULL CREATE TABLE contracts.app_settings(
 tenant_id uniqueidentifier NOT NULL,[key] nvarchar(150) NOT NULL,[value] nvarchar(max) NOT NULL DEFAULT N'{}',updated_at datetime2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT PK_app_settings PRIMARY KEY(tenant_id,[key]),CONSTRAINT FK_app_settings_tenant FOREIGN KEY(tenant_id) REFERENCES contracts.tenants(id));
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE name=N'IX_contracts_status' AND object_id=OBJECT_ID(N'contracts.contracts')) CREATE INDEX IX_contracts_status ON contracts.contracts(tenant_id,status,updated_at DESC);
IF NOT EXISTS(SELECT 1 FROM contracts.schema_migrations WHERE version=1) INSERT contracts.schema_migrations(version,name,checksum) VALUES(1,N'001_schema.sql',N'sqlserver-v1');
GO
